### ISSUE TITLE
Get sample data from json file to load into markup block's Handlebars partials

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#133]
Follow-up from #78.

If we are to use an application's Handlebars templates in the styleguide, we will need to fill its variables with sample data when it's loaded.

**Comment by JohnAlbin** [comment]
> The problem with 7eb4ae6 is that, since partials can be nested and they all contain {{modifier_class}}, the value of modifier_class set at the parent partial will be used for all nested partials too. This would cause nested modules to have the wrong markup (CSS classes) used on them.

While that may be true, that has nothing to do with this issue of adding additional variables from a json file. The `{{modifier_class}}` variable is already used in nested partials.

I've added a test to this branch and merged into master for the 2.1.0 release.

**Comment by dotherightthing** [comment]
Good stuff, thanks!

**Comment by dotherightthing** [comment]
@JohnAlbin To clarify, are partials supported already, or are they coming in 2.1.0? I tried using partials today and am seeing kss-node crash with errors.

**Comment by JohnAlbin** [comment]
Partials with data is available in 2.0.2 and later. Please open a new issue if you are experience bugs.
