### ISSUE TITLE
Allow multiple source directories

### ISSUE THREAD

**Issue by RobLoach** [kss-node/kss-node#136]
Allow KSS to read from multiple sources rather than just one source directory.

**Comment by mariohernandez** [comment]
Hi @JohnAlbin, are there plans to make this fix available on 1.x or do you have any recommendations for grabbing this fix?
Thanks.

**Comment by RobLoach** [comment]
@mariohernandez I'd recommend upgrading. Comes with some handlebar updates as well.

**Comment by mariohernandez** [comment]
Great!  Thanks @RobLoach.
