### ISSUE TITLE
Restore missing `kssModifier.markup()` method

### ISSUE THREAD

**Issue by MadLittleMods** [kss-node/kss-node#158]
I tried out the latest from the repo(even the latest release 2.0.0 alpha.4) doesn't have the `markup` function.

Please note that even `kssModifier.data.markup` is empty.

I rely on this function in order to show an example of the module with the modifier. I don't want to manually find/replace the section.markup everytime I need to use it.

This is from the [1.x branch](https://github.com/kss-node/kss-node/blob/993ab5810762211022bc80b41aef1a600e68f1b1/lib/kss_modifier.js#L53). In order to restore functionality, just add this function to bottom of `./lib/kss_modifier.js`
```
KssModifier.prototype.markup = function() {
	if (!(this.data.section && this.data.section.markup)) {
		return false;
	}

	return (this.data.section.markup() || '').replace(/\{\$modifiers\}/g, this.className());
};
```

---

For people using kss as a dependency and want to maintain legacy 1.x support and 2.x support. You can use this snippet to get the markup:
```
var markup = kssModifier.markup ? kssModifier.markup() : (function() {
	return (kssModifier.section().markup() || '').replace(/\{\$modifiers\}/g, kssModifier.className());
})();
```

**Comment by JohnAlbin** [comment]
I've reverted the commit that removed that method.
