### ISSUE TITLE
Allow templates to have a configuration file

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#164]
There are lots of per-template configurations that would be nice to have. Rather than adding lots of new flags to the command line tool, let's add a feature to read the configuration from ~a json file~ the generator.js file in the template.

Examples of nice-to-have template configurations:
- Change the default template's hard-coded JavaScript and CSS files into the default scripts and CSS specified in the config. Users could then specify a newer version of a JS or an enhanced CSS file without having to create a full custom template.
- Add variables to the default template for things like: guide_name: "kss-node style guide", homepage_name: "Overview".
- Convert the wonky CLI option `--helpers` to a template config.

```json
{
  "guide_name": "kss-node Style Guide",
  "helpers": "lib/template/helpers",
  "homepage_name": "Overview",
  "scripts": [
    "public/kss.js",
    "public/prettify.js"
  ],
  "styles": [
    "public/kss.css"
  ]
}
```

**Comment by dotherightthing** [comment]
@JohnAlbin Does or will this include support for sub templates? For example Template Z controls the styleguide look and feel, sub-template A displays a compact list of button styles, sub-template B displays a media object at three breakpoints. Thanks.

**Comment by JohnAlbin** [comment]
I'm not sure what you mean by sub-templates. How do you configure that to work?

**Comment by dotherightthing** [comment]
Hi @JohnAlbin I'm not sure as I'm using an older version of kss-node at the moment. Currently I'm working around this by putting layout divs into the styleguide Markup block.

Here's an example showing the kind of thing I'm after:

        /*
        Box

        A box is quite big and doesn't change across breakpoints so it gets the regular styleguide template.

        Markup:
        <div class="box {$modifiers}">Box</div>

        .box-feature - a featured box

        Styleguide 1.1
        */

        /*
        Button - Manual sub template

        A button is quite small and there will be many variations so we add additional styleguide layout templating to fit more on the screen.

        Markup:
        <table class="layout-styleguide-buttons">
            <tr>
                <th class="layout-col">
                    {$modifiers}
                </th>
            </tr>
            <tr>
                <td>
                    <a class="button {$modifiers}">Button inside a form</a>
                </td>
            </tr>
        </table>

        .button-next - Next button
        .button-prev - Previous button
        .button-top - Back to top button
        .button-submit - Submit button

        Styleguide 1.2
        */

        /*
        Button - Automatic sub template

        A button is quite small and there will be many variations so we add additional styleguide layout templating to fit more on the screen.

        Markup:table-2-col:
        <a class="button {$modifiers}">Button inside a form</a>

        .button-next - Next button
        .button-prev - Previous button
        .button-top - Back to top button
        .button-submit - Submit button

        Styleguide 1.2
        */

Thanks.

**Comment by JohnAlbin** [comment]
If this is what you mean: https://github.com/kss-node/kss-node/blob/master/demo/forms/forms.hbs then that is already in kss-node.

This issue is about settings per kss-node "template", e.g. the entire set of files you get when using `--init`. Not settings per markup file.

**Comment by dotherightthing** [comment]
Sorry, I didn't mean to hijack this issue. The forms.hbs link would be a potential workaround, but it's essentially the same as hand-coding supporting markup into the stylesheet. What I'm referring to is having different 'scaffolding' or layout options within the generated demos.

The supplied markup is good for small components such as buttons:

            {{#ifAny markup modifiers}}
                <div class="kss-box">{{html description}}</div>
                <table class="kss-mod-list">
                  <tr class="kss-mod-desc-group">
                    <td class="kss-mod-desc"><p>Default styling</p></td>
                    <td class="kss-mod-name"></td>
                  </tr>
                  <tr class="kss-mod-example">
                    <td colspan="2">{{modifierMarkup}}</td>
                  </tr>
                {{#eachModifier}}
                  <tr class="kss-mod-desc-group">
                    <td class="kss-mod-desc">{{html description}}</td>
                    <td class="kss-mod-name"><p>{{name}}</p></td>
                  </tr>
                  <tr class="kss-mod-example">
                    <td colspan="2">{{modifierMarkup}}</td>
                  </tr>
                {{/eachModifier}}
                </table>
                <div class="kss-markup">
                  <pre class="prettyprint lang-html">{{markup}}</pre>
                </div>
            {{else}}

I can change this markup in my custom template so that the layout works better for beefier items such as modules consisting of other components, however then I lose the ability to have a nice compact layout when I do need to document a set of buttons. What I would like is the ability to specify which set of markup to use (beefy vs buttons) on an item by item basis.

**Comment by dotherightthing** [comment]
Update: I believe that I can now do what I want with custom 'sub templates' by using the new `--custom` property option.

**Comment by rcaracaus** [comment]
WIP PR https://github.com/kss-node/kss-node/pull/180

**Comment by ROL4ND909** [comment]
@dotherightthing How did you used the --custom option?

**Comment by JohnAlbin** [comment]
If you specify `--custom mything` on the command line, then have this in your KSS comment:

```
// Title
//
// mything: option1
//
// Style guide: 4.37
```

Then kss-node will add `.mything` to the KssSection object used in the HandleBars templates. I don't have a step-by-step guide for checking for that property in your custom Handlebars template because I haven't needed such functionality myself.
