### ISSUE TITLE
Add responsive focus button for each section

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#165]
Its difficult to test a component's screen size responsiveness in the current style guide for a couple reasons:
1. There's a sidebar full of navigation decreasing the width of the component compared to the actual screen size used by the CSS media queries.
2. There's various style guide padding that's also throwing off the media queries.
3. If a component isn't at the top of the screen, shrinking the page width makes the content reflow and the component to scroll off the bottom of the screen.

We should add a button that opens a new page with just the current component (no padding or navigation) and uses the ish library to make screen resizing easier. [https://github.com/bradfrost/ish.](https://github.com/bradfrost/ish.)

**Comment by jnowland** [comment]
I currently have modified my version of kss-node to have a button that does this.

It uses the `:fullscreen` api and pseudo command - this has it's pro's and cons to it but has made debugging so much easier.

![image](https://cloud.githubusercontent.com/assets/1244314/8224295/24316a3a-15c8-11e5-8752-0faa4fe04308.png)


Once I launch this i have css that removes all the additional padding:

```
#kss-node .kss-section:-webkit-full-screen {
    max-width: initial;
    width: 100vw;
    height: 100vh;
    margin-bottom: 0;

    .kss-modifier__wrapper {
        padding: 10px 0;
        border-width:1px 0px;
    }
}
```
**Fullscreen mode:**

![image](https://cloud.githubusercontent.com/assets/1244314/8224303/4117e48a-15c8-11e5-8fd3-241beb0dd41a.png)



Would this approach be suitable for this project?

**Comment by JohnAlbin** [comment]
@jnowland Sweet. Care to share the code? :-D

**Comment by jnowland** [comment]
@JohnAlbin I'll try to find some time this week.

**Comment by jerseycheese** [comment]
Me gusta.

**Comment by JohnAlbin** [comment]
From a duplicate issue, #219:

> Quick and dirty component you can add that will isolate components for you if you need to develop responsively. https://github.com/JordanDDisch/KSS-Isolate"

**Comment by supasympa** [comment]
This is what I did:

```
jQuery(function($) {
  $(document).ready(function() {
    $('.kss-modifier-example').each(function(i, mod) {

    console.log(arguments);

      var $btn = $('<button data-to-isolate="true" style="margin:20px;">Toggle isolate</button>');

      $btn.on('click', function() {
        var $this = $(this);
        var currentValue = $this.attr('data-to-isolate');

        $this.attr('data-to-isolate', currentValue == 'true' ? 'false' : 'true');

        if(currentValue == 'true'){
          $this.parent().wrap('<div id="kss-isolated-foo"></div>');
          $('body').prepend($this.parent());
          $('.kss-wrapper').hide();
        }else{
          $('#kss-isolated-foo').replaceWith($this.parent());
          $('.kss-wrapper').show();
        }

      });

      $(mod).append($btn);
    });
  });
});

```

**Comment by risker** [comment]
I have been playing around with this need, too. I've hacked together a generator that generates a html page for every modifier. Then the modifiers are rendered into the component/collection pages through iframes.

Pros of this implementation:
- Rendering components in iframes makes it easier to see media queries in action in the styleguide (#165)
- No duplicate ID collisions (can happen when demoing tabs, for example, where IDs are used for navigation)
- Can view every modifier standalone, for simpler development and visual regression testing (#282, #175)

Cons:
- Generates awfully slow (about 30s with my current component library)
- Loading performance is sluggish when a page has lots of iframes

**Comment by JohnAlbin** [comment]
@risker Yeah, I've tried that before too. The load time with lots of iframes totally sucks. :-( Otherwise, it would be perfect.

**Comment by JohnAlbin** [comment]
Its currently difficult to apply CSS when in fullscreen mode.

Also, when I used a simpler CSS/JS implementation of full window (instead of full screen), it doesn't take over the window preventing you from using other windows.

So, that's why I went with CSS/JS combo instead of fullscreen API.
