### ISSUE TITLE
Upgraded to node.js v0.12.0 breaks (node-sass)

### ISSUE THREAD

**Issue by himynameisdave** [kss-node/kss-node#170]
Just found that upgrading my node.js version to [the latest stable release, v0.12](http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/) causes node-sass to break with the following error. Not sure if this is the right place to post this error, just wanted the community to see it.

![screen shot 2015-02-09 at 11 44 42 am](https://cloud.githubusercontent.com/assets/4298089/6110643/13bbd80c-b051-11e4-9626-7b3137137a8f.png)

Reverting back to 0.10 of node fixes the issue.

My example is using [grunt-styleguide](https://www.npmjs.com/package/grunt-styleguide) which uses this module as a dep.

**Comment by JohnAlbin** [comment]
node-sass 1.x doesn't work with node.js 0.12. I had to upgrade node-sass to 2.x to fix this issue.
