### ISSUE TITLE
rootNumber deprecation warning not working

### ISSUE THREAD

**Issue by trodrigues** [kss-node/kss-node#171]
Not sure if this happens because rootNumber in my case was being used as a parameter to eachSection, but it failed with the same error I had reported in #102 (which was even weirder because I had reported that error and checked that it was fixed), instead of showing a deprecation warning.

Not sure if it's important enough to fix, but just thought I'd log something here even if as a reference for others who might come across this.

**Comment by JohnAlbin** [comment]
> Not sure if this happens because rootNumber in my case was being used as a parameter to eachSection

Yeah, there's not much I can do there. The deprecation warning works when you try to print `{{rootNumber}}`, but I don't have a way to check `{{eachSection rootNumber}}`. :-\
