### ISSUE TITLE
Handlebars 3.0.0

### ISSUE THREAD

**Issue by RobLoach** [kss-node/kss-node#172]
:dancer:

**Comment by JohnAlbin** [comment]
A quick uptick of the package.json to use Handlebars 3 doesn't throw any test failures. Hmmm…

**Comment by JohnAlbin** [comment]
See https://travis-ci.org/kss-node/kss-node/builds/50613902

**Comment by JohnAlbin** [comment]
FYI, I can't find any docs or blog post about what's in HandleBars 3. :-\
