### ISSUE TITLE
no custom styles applied to styleguide 

### ISSUE THREAD

**Issue by chloeleichen** [kss-node/kss-node#177]
I followed the instructions in the doc to create a style-guide,  using the example source files from Flower Power(https://github.com/JohnAlbin/flower-power), here is what happened: 
kss-node ./sass styleguides --template ./template 

Generating your KSS style guide!

 * KSS Source  : /Users/chloe/Sites/flower-power/sass
 * Destination : /Users/chloe/Sites/flower-power/styleguides
 * Template    : /Users/chloe/Sites/flower-power/template
 * Helpers     : /Users/chloe/Sites/flower-power/template/helpers

...Parsing your style guide:
 - /Users/chloe/Sites/flower-power/sass/components/_flower.scss
 - /Users/chloe/Sites/flower-power/sass/styles.scss
...Determining section markup:
 - 1.1: inline markup
 - 1.2: inline markup
 - 1.3: inline markup
 - 2: inline markup
 - 2.1: inline markup
 - 2.2: inline markup
 - 2.3: inline markup
 - 2.4: inline markup
 - 2.5: inline markup
 - 2.6: inline markup
...Generating style guide sections:
 - section 1 [ Flower ]
 - section 2 [ Flower (deconstructed) ]
 - homepage

Generation completed successfully!

Then when I went to the styleguide, I notice that there is no css apart from the kss.css. Am I missing anything here? It's driving me mad. Thanks!

**Comment by becca-studyblue** [comment]
Did this issue get resolved somehow?  I'm struggling with the same problem.

**Comment by jjalonso** [comment]
Same here. Any update?

**Comment by RobLoach** [comment]
KSS 2 or 3?

**Comment by chloeleichen** [comment]
you need to pass in your css file (compiled) as a commandline argument, since kss does not compile css
