### ISSUE TITLE
Give template ability to prepare itself or KssStyleguide before generate()

### ISSUE THREAD

**Issue by dotherightthing** [kss-node/kss-node#182]
I've created a custom template which uses some open source 3rd party code. 

The template was created with: `kss-node --init CUSTOM_TEMPLATE_NAME`

The 3rd party code is managed in `bower.json` and downloaded into the template's `public` folder using `bower install` (via the config file `.bowerrc`). When generating the styleguide KSS node already copies the contents of the `public` folder to the output directory, so the links from my template to the 3rd party code do not break.

But having to manually `cd` into the `CUSTOM_TEMPLATE_NAME` directory to run `bower install` is an extra step I'd rather not take.

Is there a way for KSS node to automatically run `npm install` or `bower install` when generating the styleguide? 

(I've also posted some related info on [Stackoverflow](http://stackoverflow.com/questions/28865437/specifying-the-location-of-bowerrc-when-calling-bower-install)).

**Comment by JohnAlbin** [comment]
From #245:
> Right now we tell the parser about custom properties. While we could tell the parser to run a callback on the contents of the custom property (so you could render the markdown), I don't think that would be useful in the general case of "I want to do something with the custom property."
>
> The only way to ensure the most flexibility is to give the template a chance to modify the parsed KssStyleguide object before the generator makes the HTML pages.

So, I've decided we can add a prepare() method to the KSS generator objects that would allow the template time to prepare itself or to modify the just-parsed KssStyleguide object.
