### ISSUE TITLE
Add method to return JSON of KssStyleGuide

### ISSUE THREAD

**Issue by operatino** [kss-node/kss-node#190]
Hi,

Would be really great if your Module API could return JSON as and parsing output, so anybody could use custom renderers for the output documentation. This will drastically improve flexibility of kss-node module.

Currently I know only one CSS documentation parser module that is returning JSON as output https://github.com/darcyclarke/DSS. But it is not so widely adopted like KSS.

**Comment by delebash** [comment]
The [Api](http://kss-node.github.io/kss-node/api/2.0.x/module-kss.KssSection.html) does have a JSON method attached to the Sections object(JSON(customProperties) → {Object}), not sure how to use it from the command line.  Here is a [gist ](https://gist.github.com/delebash/df7a9249d034e2573057) you can run using node, I just copied the demo folder from kss-node then ran npm install kss fs-extra, copy this gist, save it as [filename].js then run node [filename].js, it should create a docs folder with kss.json file

**Comment by operatino** [comment]
Great, thank you for the insights!

I recently made [DSS integration plugin](https://github.com/sourcejs/sourcejs-contrib-dss) to our [SourceJS](http://sourcejs.com/) Style Guide Platform. Will try to create KSS integration as well.

Thought it will be still useful to have direct method, for getting full JSON data from the parser, without constructing it by hand.

**Comment by JohnAlbin** [comment]
I was just thinking about a new feature that would allow a partial re-build of the style guide if one file gets updated. But that would required that the existing style guide object be cached somehow. Obviously being about to export and import a full JSON representation of the KssStyleGuide object would be best.
