### ISSUE TITLE
Access custom property from handlebars helper

### ISSUE THREAD

**Issue by dotherightthing** [kss-node/kss-node#191]
I am using custom properties to control the way that KSS snippets are presented in the styleguide.

Currently I am simply outputting the value of my `ct_layout` property into the template as a CSS classname.

However to achieve more radical layouts I'd like to change the markup output based on the value of `ct_layout`.

I am using the following helper, [based on this post from StackOverflow](http://stackoverflow.com/a/16315366), to query the value of `ct_layout`:

        module.exports.register = function(handlebars) {
            handlebars.registerHelper('ifCond', function (v1, operator, v2, options) {
                console.log(v1, operator, v2);
            });
        };

Usage:

        {{#ifCond ct_layout '==' 'main'}}MAIN{{/ifCond}}

However, `ct_layout` is always logged as `undefined`:

        undefined '==' 'main'

What is the correct way to access this custom property?

Thanks

**Comment by JohnAlbin** [comment]
Good question!

**Comment by JohnAlbin** [comment]
Inside `{{eachSection [var]}}`, you can just use `{{layout}}` to access a custom KSS property name called "layout".

But note that handlebars variables are context-sensitive. If you are inside an additional block-level expression, you'll need to change how you access the variable. See handlebarsjs.com#block-expressions for more info.

**Comment by JohnAlbin** [comment]
I've added a `{{consoleLog}}` helper that outputs all the variables available in the current context of a Handlebars template. Optionally, you can do `{{consoleLog variable}}` to just output the value of one variable in the current context.
