### ISSUE TITLE
Create any missing parent directories of destination

### ISSUE THREAD

**Issue by ethikz** [kss-node/kss-node#193]
I am trying to run kss-node from CLI which will work if I am setting the destination to be the working directory but when I try to set it as a different directory and the directory does not yet exist, it will not create those folders.

My error is ````ENOENT, no such file or directory````

The command I'm running from gulp is:
````kss-node src/main/webapp/styleguide-src/app/assets/css target/web/styleguide --config src/main/webapp/styleguide-src/styleguide-template/config.json````

My config.json is:
````
{
  "source" : ".",
  "template" : "../styleguide-template",
  "css" : [
    "assets/css/main.css"
  ]
}
````

The above command will not work until ````target/web```` is created manually or by some other process.  Why will it not create those directories itself?  I know it creates the directories for the assets like css/js.

**Comment by JohnAlbin** [comment]
Funnily enough, ran into this same problem today.

**Comment by ethikz** [comment]
lol ok good, glad it just wasn't me.  I had to use mkdirp but that even doesn't work sometimes :frowning:
