### ISSUE TITLE
Is it possible to use array in styleguide comment?

### ISSUE THREAD

**Issue by Viktori** [kss-node/kss-node#198]
I want to create page with base colors. And it's not usable to write a lot of similar rows of code:
```
<div style="background:#{$primary-color}" class="styleguide-color">$primary-color</div>
<div style="background:#{$primary-color-inverted}" class="styleguide-color">$primary-color-inverted</div>
...
```
I want to use loop in styleguide comments. For example:
```
$colors: "c-middle-blue", "c-dark-blue", "c-light-blue", "c-green";
for color in colors {
<div class="{$color}"></color>
}
```

**Comment by JohnAlbin** [comment]
KSS comments are just CSS or Sass comments. They are not programming constructs.

But looking at your code sample, you have `#{$primary-color}`. I don't know what kind of code that is, but I suspect it isn't a CSS comment. Possibly you meant a Handlebars template? Handlebars can do loops. See http://handlebarsjs.com/
