### ISSUE TITLE
Custom HTML issue

### ISSUE THREAD

**Issue by ethikz** [kss-node/kss-node#207]
I updated kss to 2.1.0 and now when I run the generation it throws an error but still compiles.

````
kss-node src/main/webapp/styleguide-src/assets/css target/styleguide --config src/main/webapp/styleguide-src/styleguide-template/config.json

/Users/jchris/Development/web/src/main/webapp/styleguide-src/styleguide-template/index.html:1
(function (exports, require, module, __filename, __dirname) { <!DOCTYPE html>
                                                              ^
````

**Comment by JohnAlbin** [comment]
You've only pasted half the error message, so I don't know what error is occurring.

**Comment by ethikz** [comment]
````
 * Helpers     :


/Users/jchris/Development/web/src/main/webapp/styleguide-src/styleguide-template/index.html:1
(function (exports, require, module, __filename, __dirname) { <!DOCTYPE html>
````

This is all that is displayed

**Comment by JohnAlbin** [comment]
In your first comment you have a line that says:
```
                                                              ^
```
There's always a line after that the tells you where the error occurred. I need the entire error message including the backtrace.

**Comment by ethikz** [comment]
Oh ok well I haven't been able to reproduce it yet.  You can close this and if I notice it again I'll post a new issue.

Thanks.
