### ISSUE TITLE
Handlebars error messages

### ISSUE THREAD

**Issue by dotherightthing** [kss-node/kss-node#210]
Is it possible for kss-node to output more descriptive error messages when there is a problem and it can't generate the styleguide due to a Handlebars issue?

__Example 1__

* I reference a handlebars partial in `Styleguide index.subindex` like so: `{{> index.subindex}}`
* I then rename `Styleguide index.subindex` to `Styleguide index.subindex1`
* The styleguide generation now fails

__Example 2__

* I make a mistake in my handlebars code, eg I close an `{{#unless}}` with an `{{/if}}`
* The styleguide generation now fails

Thanks,
Dan

**Comment by JohnAlbin** [comment]
I tried Example 2 and got:

```
Error during generation

{ [Error: unless doesn't match if - 24:3]
  description: undefined,
  fileName: undefined,
  lineNumber: 24,
  message: 'unless doesn\'t match if - 24:3',
  name: 'Error',
  number: undefined,
  column: 3 }
```

Can you describe how you would like to improve this?

**Comment by dotherightthing** [comment]
Ah, ok - sorry, it must be a limitation of [subgrunt](https://github.com/tusbar/grunt-subgrunt) which I am using to run [my styleguide template](https://bitbucket.org/chrometoaster/ct__kss-node-template) related tasks from the main project.
