### ISSUE TITLE
Space-dash-space in comment generates a modifier when no other modifiers are specified

### ISSUE THREAD

**Issue by dotherightthing** [kss-node/kss-node#211]
When I use strings containing dashes in an item's description (i.e. the text following the item name and preceding the `Markup:`), kss-node outputs the string as a modifier.

Input:

    /*
    Item
    
    Something - SomethingElse.
    
    Markup:
    <div class="{{modifier_class}}"></div>

    Styleguide 1.0
    */

Output:

* Default example
* Modifier: `Something - SomethingElse.`

Thanks.

**Comment by JohnAlbin** [comment]
> When I use strings containing dashes in an item's description, kss-node outputs the string as a modifier.

Um, yeah, it does. That's what the KSS spec says to do.

**Comment by dotherightthing** [comment]
Um, no - here's what the [spec](https://github.com/kneath/kss/blob/master/SPEC.md) says to do:

> The modifiers section
> If the UI element you are documenting has multiple states or styles depending on added __classes__ or __pseudo-classes__, you should document them in the modifiers section.
> `// :hover             - Subtle hover highlight.`
> `// .stars-given       - A highlight indicating you've already given a star.`
> `// .stars-given:hover - Subtle hover highlight on top of stars-given styling.`
> `// .disabled          - Dims the button to indicate it cannot be used.`

The four examples above illustrate documentation of a pseudo class and three classes. 

Compare this to the following, which does not begin with a colon or a period and therefore does not denote a pseudo or actual class:

> Something - SomethingElse.

Thanks,
Dan

**Comment by JohnAlbin** [comment]
The spec also says this. From https://github.com/kss-node/kss/blob/spec/SPEC.md#the-parameters

> If the mixin takes parameters, you should document each parameter and describe what sort of input it expects (hex, number, etc).
> 
> ```
> // $start - The color hex at the top.
> // $end   - The color hex at the bottom.
> ```

In that example, it is showing the syntax for a Sass variable `$variable`. But it also needs to accept Less variables `@Less` and whatever Stylus uses and whatever CrazySyntaxCSSPreprocesor uses for its variables. In other words, I have to accept anything before the ` - ` (space dash space) as a valid modifier/parameter.

**Comment by dotherightthing** [comment]
@JohnAlbin Thanks for the clarification, I forgot that you had to support other preprocessors!
