### ISSUE TITLE
$modifier_class not rendering in output code or 'example markup'

### ISSUE THREAD

**Issue by createdotmatt** [kss-node/kss-node#213]
Hi,

I have recently updated to v2.0 and so I have updated my docs / comments to use {{$modifier_class}} rather than {{$modifiers}}.

The modifier classes are not being output in my code. e.g `// <button class="btn {{$modifier_class}}">Button</button>` becomes `<button class="btn ">Button</button>`. Meaning all my buttons look the same!

I have the following in my template;
```
{{#eachModifier}}
	<div class="kss-modifier__name kss-style">
  		{{name}}
	</div>
	
	<div class="kss-modifier__description kss-style">
  		{{{description}}}
	</div>

	<div class="kss-modifier__example">
		{{{markup}}}
	</div>
{{/eachModifier}}
```

and here's a screenshot of why this matters
![screenshot 2015-06-08 09 48 35](https://cloud.githubusercontent.com/assets/7290654/8031071/92d86be4-0dc3-11e5-9c55-b58cdeba519b.png)

Are there any docs on updating versions? A changelog of any sort? Thanks for the help, Matt.

**Comment by dotherightthing** [comment]
@createdotmatt

The correct syntax is `{{modifier_class}}` (without the `$`).

AFAIK that change happened @ https://github.com/kss-node/kss-node/releases/tag/v2.0.0-alpha.1

I don't know if there's an all-in-one summary anywhere, I just read all the release notes @ https://github.com/kss-node/kss-node/releases

Cheers,
Dan

**Comment by createdotmatt** [comment]
Thanks @dotherightthing, that'll teach me for not reading the docs properly!
