### ISSUE TITLE
Custom option to specify the depth at which anchors are used rather than hyperlinks

### ISSUE THREAD

**Issue by dotherightthing** [kss-node/kss-node#214]
I like to organise my styleguide via categories like "base", "modules" etc.

I have a lot of items inside each category.

Currently all the items in each category are output on one page. That page gets pretty long and seems to slow the browser/OS down.

Would it be possible to specify the depth at which anchors are used rather than hyperlinks? At the moment that would be depth 2, where depth 1 is `Styleguide modules`, accessible via a hyperlink and depth 2 is `Styleguide modules.box`, accessible via an anchor link.

Alternatively, is there a way to do this in my custom template?

Thanks.

**Comment by jerseycheese** [comment]
See #175...

**Comment by dotherightthing** [comment]
Ah, thanks!
