### ISSUE TITLE
--placeholder does not accept blanks

### ISSUE THREAD

**Issue by bm2u** [kss-node/kss-node#215]
Hi there, I am using the latest version (2.1.0). Unfortunately the placeholder argument (string) does not accept spaces/blanks.

--placeholder 'sub sti tu tion' // does not work
--placeholder 'substitution' // does work

Keep up the excellent work!

**Comment by JohnAlbin** [comment]
Huh. I haven't verified this bug. It just seems odd considering the default value is `[modifier class]`.

**Comment by JohnAlbin** [comment]
I tested this and it works fine. Here's a screenshot using `--placeholder 'sub sti tu tion'`:

<img width="628" alt="screen shot 2016-02-11 at 10 33 39" src="https://cloud.githubusercontent.com/assets/33429/12968313/0f0e2f00-d0ab-11e5-8210-a498aea160b8.png">

**Comment by bm2u** [comment]
@JohnAlbin: Thanks for your review. I figured out what I did wrong. First of all I had a global config file for all needed arguments of kss-node. 

Among others the placeholder argument with: 
<code>placeholder: '[replace with modifier]'</code>

By running kss-node via gulp with: 
<code>kss-node ... + '--placeholder ' + config.placeholder + '... </code>

I forget to put extra double quotes around to pass the argument as a string. 

It should be:
 <code>kss-node ... + '--placeholder "' + config.placeholder + '"... </code>.
