### ISSUE TITLE
Section Generation Fails if "root level" of section is not documented

### ISSUE THREAD

**Issue by Undistraction** [kss-node/kss-node#216]
When using dot-separated section names, generation of the sections fails:

For example I have two comment blocks - one for Icon buttons and one for buttons:

```
// Button
//
// Your standard button suitable for clicking.
//
// :hover   - Highlights when hovering.
//
// Markup:
//  <button class="{{modifier_class}}">Label</button>
//
// Styleguide: generic.buttons.basic

// Icon Button
//
// Button containing an icon
//
// :hover   - Highlights when hovering.
//
// Markup:
//  <button class="{{modifier_class}}">
//    <span class="Icon fa fa-fw fa-search"></span> Label
//  </button>
//
// Styleguide: generic.buttons.icon
```

In this instance, no sections other than overview are generated:

![sections](https://dl.dropboxusercontent.com/u/316978/styleguide.png)

```
...Determining section markup:
 - generic.buttons.basic: inline markup
 - generic.buttons.icon: inline markup
 - generic.links: inline markup
...Generating style guide sections:
 - section generic [ Unnamed ]
 - homepage
```

If I remove the dots from the sections, generation succeeds. If I have another comment block that defines the parent sections (in this case, one that defines `generic` and another that defines `generic.buttons`), then the dot notation does work.

I'm using v.2.1.0

**Comment by fokusferit** [comment]
Hi,

I've had the same issue, first time. 

I've solved this , today, with defining the missing "styleguide" sections, e.g.

```
// Generic
//
// Your generic elements
//
// Styleguide: generic

// Buttons
//
// Your button elements
//
// Styleguide: generic.buttons
```

hope this solves it.

**Comment by JohnAlbin** [comment]
This is a fairly major bug. But @fokusferit is the correct work around. Thanks for posting that!

**Comment by fokusferit** [comment]
@JohnAlbin I've also realized that the Components , e.g. "generic.buttons.icon" are already parsed and added into the section.html file but are not parsed into the main Navigation. 

I guess it has something to do with how the parsing works internally, as in https://github.com/kss-node/kss-node/blob/bd16fe1f3375c42ebaa4beae15467815c35c1921/generator/handlebars/helpers.js 

```
  /**
   * Loop over each section root, i.e. each section only one level deep.
   */
  handlebars.registerHelper('eachRoot', function(options) {
    var buffer = '',
```
