### ISSUE TITLE
Ability to hide sidebar menu

### ISSUE THREAD

**Issue by rcaracaus** [kss-node/kss-node#219]
In order to work with components that have mediaqueries it would be useful to hide the sidebar menu and remove padding around components.

**Comment by fokusferit** [comment]
You can do this with an additional CSS file. 
1. Create a separate css-file with your styling, e.g. Media Query specific behavior
2. Add this CSS file with -css 

The specific classes of the template can be found in kss/generator/handlebars/template/index.html . But I think, it would make sense to look into the index.html file and create a new template with the existing handlebars partials. 
Therefore:

1. Create your own index-html template
2. Use --template / -t to add your specific template

**Comment by rcaracaus** [comment]
Quick and dirty component you can add that will isolate components for you if you need to develop responsively. https://github.com/JordanDDisch/KSS-Isolate
