### ISSUE TITLE
Support consolidate.js templates

### ISSUE THREAD

**Issue by matthewferry** [kss-node/kss-node#229]
Feature request for consolidate.js engine option when using the custom template option instead of forcing handlebars. Currently I'm running kss to build the css documentation portion of our static styleguide site, which includes other guides such as content guides and brand guides. I've been using swig for the static site templates and would love to be able to just keep it all the same; imagine others may want to include kss in projects that are using other template engines?

**Comment by JohnAlbin** [comment]
kss 2.1.0 already has support for additional template engines built-in. Each template engine is called a type of KssGenerator object.

Take a look at how the current default template chooses the Handlebars Generator to use: https://github.com/kss-node/kss-node/blob/master/generator/handlebars/template/template_config.js

Generators can either be bundled with kss-node or distributed as separate npm packages.

**Comment by madeofpeople** [comment]
@JohnAlbin your link above 404s.

This is excellent news though.

**Comment by JohnAlbin** [comment]
kss-node 3.0.0 is almost out and the file got renamed. New location is: https://github.com/kss-node/kss-node/blob/master/builder/handlebars/builder.js

**Comment by madeofpeople** [comment]
Good news all-round

**Comment by matthewferry** [comment]
Nice, can I close this then since it's included in https://github.com/kss-node/kss-node/issues/256 ?

**Comment by JohnAlbin** [comment]
The KssBuilder class and its sub-classes in kss-node would allow you to write a builder that uses consolidate.js templates.

So, @matthewferry, is that what you were requesting? If so, yes, we can close this issue.

Or did you want a pre-built consolidate.js builder included with kss-node? I would welcome a PR for this.

**Comment by matthewferry** [comment]
This would work for me. Thanks!
