### ISSUE TITLE
"Error: stdout maxBuffer exceeded" when walking large repositories

### ISSUE THREAD

**Issue by sgregson** [kss-node/kss-node#232]
Similar to francisbyrne/grunt-svn-export#1, enumerating each file in a large codebase leads to a `Error: stdout maxBuffer exceeded.`

Happy to enter PR for adding execOptions as in that bug's pull request (grunt-svn-export/pull/2/). Alternatively, an option to suppress or summarize the file-parsing output stage of the task would work. Preference?

**Comment by JohnAlbin** [comment]
> Alternatively, an option to suppress or summarize the file-parsing output stage of the task would work. Preference?

Actually, we already did that. The new default output in kss 2.2.0 will be a single line. You can use the `--verbose` option if you want to see a full list of steps kss-node took.
