### ISSUE TITLE
Lock version of yargs

### ISSUE THREAD

**Issue by wrumsby** [kss-node/kss-node#236]
I ran into some problems with kss-node version 2.1.0 that seem to be caused by yargs version 3.30.0 which was _just_ released. I resolved these issues by adding a dependency on yargs version 3.29.0.

Without doing this running kss-node complains:

```
Unknown argument: xdemo
```

The problem here seems to be caused by a bug in yargs, which I will try to properly diagnose, but I'd suggest that it's a good idea to lock the version of yargs and other dependencies.

**Comment by jon301** [comment]
+1
Got the same issue here

**Comment by blandine** [comment]
+1

**Comment by pyryjook** [comment]
+1

**Comment by aellison** [comment]
+1

**Comment by razvanpavel** [comment]
+1

Thanks a lot. This seemed really really off.

**Comment by jtwalters** [comment]
Yes, please tag a release with the yargs dependency locked down. We use kss-node in an automated build environment and this is a critical issue.

**Comment by RobLoach** [comment]
https://github.com/kss-node/kss-node/pull/238 has a passing fix..

**Comment by jon301** [comment]
Hi,

Any updates on this ?

**Comment by JohnAlbin** [comment]
> It's probably advisable to npm-shrinkwrap 

Hell, yes. That's why I didn't notice this problem until today. My projects all do `npm shrinkwrap --dev` and then commit the npm-shrinkwrap.json to Git. You should too.

See https://github.com/kss-node/kss-node/wiki/npm-quick-start-guide#sharing-a-project for a fuller description.

**Comment by JohnAlbin** [comment]
Thanks for the PRs that fixed this issue!

Contributors++
