### ISSUE TITLE
Add @RobLoach as a maintainer

### ISSUE THREAD

**Issue by RobLoach** [kss-node/kss-node#241]
I'm willing to help maintain `kss-node`. Particularly in code review, pushing passing pull requests forwards, releasing new versions, etc. Including getting the currently broken build in a working state.

@JohnAlbin Mind adding me in both the GitHub and [the npm module](https://www.npmjs.com/package/kss)?

**Comment by JohnAlbin** [comment]
Given #238, I think you've proven your worth. :-)

**Comment by JohnAlbin** [comment]
Done!

**Comment by RobLoach** [comment]
:+1:
