### ISSUE TITLE
Add Handlebars 4.0 support

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#244]
I tested Handlebars 4.0 with kss-node and the nav menu does not render properly in our default template. Specifically, the child items of the current section do not appear when using Handlebars 4.0.5, but they do appear when using Handlebars 3.0.3.

**Comment by ryuran** [comment]
Impatient to have this fix in a release.

**Comment by JohnAlbin** [comment]
It turns out Handlebars 4 handles `../` differently than 3 and earlier.

**Comment by JohnAlbin** [comment]
I can't break people's custom templates by bumping Handlebars to v4 inside the 2.x releases. I'll have to release it with a 3.x name.

**Comment by jtwalters** [comment]
@JohnAlbin As you mentioned, it breaks custom templates, once we bumped from kss 2.1.0 to 2.1.1. 

Shouldn't you have saved the handlebars version bump for kss 3.x?

**Comment by JohnAlbin** [comment]
The master branch is now for 3.x work. I've created a 2.x branch for bug fixes after 2.3.1.

Do you want me to create a 3.0.0-alpha.1 tag? Alternatively, your package can just use HEAD by specifying "kss-node/kss-node" as the version in package.json.

**Comment by jtwalters** [comment]
I was just pointing out that you released handlebars 4 in `kss-node` tagged 2.1.1, which was a breaking change compared to `kss-node` tagged 2.1.0. It could potentially be problematic for folks who depend on ^2.1.0 and use a custom template.

https://github.com/kss-node/kss-node/blob/v2.1.1/package.json

**Comment by JohnAlbin** [comment]
@jtwalters Yes, I didn't notice that Handlebars 4 broke 2.1.1 until 4 days after I released it. I should have tagged a 2.1.2 with the fix, but I didn't think about it.

Anyway, 2.2.0, 2.3.0 and 2.3.1 have all been released now and use Handlebars 3 or earlier. So anyone who depends on `^2.1.0` will get 2.3.1.

**Comment by JohnAlbin** [comment]
@ryuran You were the "impatient" one. Do you want an alpha release of 3.x so you can use Handlebars 4 now?
