### ISSUE TITLE
Make nav-depth option work for any Handlebars template

### ISSUE THREAD

**Issue by astronati** [kss-node/kss-node#264]
Console shows following error when I try to create a styleguide using `--nav-depth` option:
`Unknown argument: nav-depth`

Version: 2.3.3

**Comment by JohnAlbin** [comment]
I tried `kss-node --nav-depth 2 --xdemo --destination new` and it worked perfectly.

@astronati, are you using a different `--template`? Because `nav-depth` is an option of the default Handlebars template.

**Comment by astronati** [comment]
Yes, I am. Does the documentation explain that? There will be the possibility to use it in the next future for custom templates?

**Comment by JohnAlbin** [comment]
Hmm… I've looked at this and I don't see a reason why this feature of the default Handlebars template can't be moved to the Handlebars generator.

**Comment by JohnAlbin** [comment]
Added this to 2.4.0. You should be able to use it with any custom Handlebars template now.
