### ISSUE TITLE
Generator not passing '...Parsing your style guide:'

### ISSUE THREAD

**Issue by liam-swinney** [kss-node/kss-node#265]
I'm running the following on the command line:

```
./node_modules/.bin/kss-node --source "BH.Styles/bh.less" --css "bh.css" --verbose --homepage styleguide/styleguide.md
```

Tihs provides the following output:

```
Generating your KSS style guide!

 * KSS Source  : c:****\BOSHost.Styles\bosHost.less
 * Destination : c:****\styleguide
 * Template    : c:****\node_modules\kss\generator\handlebars\template

...Parsing your style guide:
```

(c:***\* hiding my path)

This ends here,  creates the styleguide public folder but nothing else.

I'm running:
`node 5.4.1`
`npm 3.5.3`

I'm wondering if anyone knew what was happening thanks!

**Comment by JohnAlbin** [comment]
It doesn't show an error after the "...Parsing your style guide:" line?

My only guess is that it is choking on something in your `BH.Styles/bh.less` file. Either post that file here (so we can test) or test it yourself by trying a simpler file instead of your bh.less to see if that works.

**Comment by mahmoudilyan** [comment]
This is the same with me too, I'm using sass and the problem is still

**Comment by JohnAlbin** [comment]
> This is the same with me too

And my response is the same too. If either of you can give me more details, I can help you fix it. Otherwise, there is nothing I can do.
