### ISSUE TITLE
Add Twig.js builder and class

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#272]
The builder API has undergone a lot of improvements/simplification in master (the future 3.x version). It should be straight-forward to add a different template engine.

Drupal 8 uses the Twig template engine, so using Twig.js (a JS port of the PHP Twig template project) would be pretty useful.

**Comment by Rodrigo-Ludgero** [comment]
Good news and great job, it would be nice to use **nunjucks.js**, thanks.
:+1:

**Comment by JohnAlbin** [comment]
We need to finish #275 first.
