### ISSUE TITLE
Style.css Not Generated When Using SASS

### ISSUE THREAD

**Issue by sam3k** [kss-node/kss-node#28]
This won't generate the style.css:
kss-node sass docs/styleguide --sass sass/styles.scss

But this does:
kss-node sass docs/styleguide --css css/styles.css

My sass folder looks something like:
- sass/
  - styles.scss
  - partials/
    -  components.scss

**Comment by JohnAlbin** [comment]
If you are landing here from a random Google search, this is a fixed issue in the recently released 2.0 version of a very-much-now-maintained kss-node. :)

**Comment by chengyin** [comment]
@JohnAlbin Hey John, I'm still hitting the said issue with LESS files. The demo project ran fine. In the generated HTML of mine, the only CSS that was included was kss.css, there was no trace for my own css file.
