### ISSUE TITLE
Generate a page for each item to aid visual regression tools

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#282]
Currently we group all style guide sections by their root reference name. e.g. All `form.*` sections go on a `section-form.html` page.

For visual regression tools, it would be handy to have a single page for a single section so that it can be tested in isolation.

Since groups of sections are put on a `section-*.html` page, we should use a different filename prefix for an individual section. e.g. `item-*.html`

**Comment by ctaepper** [comment]
yea, this will be great feature

**Comment by iampuma** [comment]
+1

**Comment by Nodles** [comment]
+1

**Comment by JohnAlbin** [comment]
Fixed! This is now in the master branch.

**Comment by jnowland** [comment]
@JohnAlbin What tools are you using for the visual regression testing?

**Comment by ctaepper** [comment]
@jnowland look at this one: https://github.com/galenframework/galen

**Comment by ryuran** [comment]
@ctaepper this one do not compare a rendering to a older one. It only check position of elements/block.

[Wraith](https://github.com/BBC-News/wraith) can be a solution.

**Comment by ctaepper** [comment]
@ryuran galen sure does have screenshot comparison, however it goes one step further: with its test syntax, you wouldnt even need screenshots, because you can completely define how the layout should look like, taking browser differences in account. imho far more flexible that just screenshot comparison

**Comment by ryuran** [comment]
@ctaepper ho great. I should to test it.
Visual non-regression test tools are not enough used.
