### ISSUE TITLE
Add --json option to output JSON of style guide

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#284]
I suppose somebody, somewhere may just want the KSS style guide data stuffed into a JSON file so that it can build the style guide later.

Since kss.traverse() and kss.parse() just output a JSON-like object, it's trivial to create a "kss builder" that outputs to a single JSON file.

**Comment by ryuran** [comment]
Why not use json for kss output.
And use a builder to use this json and build the html/css.

Json can feed twig, handlebars, etc.

And we can remove builder from the kss-node package.

kss-node read sources and make a json
kss-builder use kss json and build html/css

**Comment by airtonix** [comment]
will this leave the markup of each section uncompiled or compiled?

Problem i have with `kss.traverse` at the moment is that i get a json output that results in uncompiled partials where these partials reference other sections for re-use.

End result is that I have to essentially recreate KSS just to have these partials rendered but only result in a json file outputed.
