### ISSUE TITLE
Error 404 in a link of Javascript API

### ISSUE THREAD

**Issue by nucliweb** [kss-node/kss-node#286]
The link to `KssStyleGuide` in **Javascript API** go to error 404, because the link have uppercase **G** (module-kss.KssStyle**G**uide.html) and the file have in lowercase **g** (module-kss.KssStyle**g**uide.html)

**Comment by JohnAlbin** [comment]
hmm… that's probably caused by building the files on my Mac with its case-insensitive file system.

Thanks, @nucliweb!

**Comment by JohnAlbin** [comment]
Fixed! Thanks again, @nucliweb.
