### ISSUE TITLE
In Handlebars builder, change index.html to index.hbs

### ISSUE THREAD

**Issue by marienvo** [kss-node/kss-node#289]
Would it be possible to rename the index.html to index.hbs? Since it's a Handlebars template and not an HTML file. This way the file can be opened as such, so you can enable syntax highlighting ;)

**Comment by RobLoach** [comment]
Which branch are you on? The `demo` already has .hbs files.

**Comment by marienvo** [comment]
I mean the template for building the HTML (builder/handlebars/index.html), not the demo files.

**Comment by JohnAlbin** [comment]
That actually seems quite reasonable. I'll add it to the list!

**Comment by JohnAlbin** [comment]
Feel free to submit a PR!
