### ISSUE TITLE
Is there any way I can get description  in Markup?

### ISSUE THREAD

**Issue by studiomohawk** [kss-node/kss-node#290]
I want to do something like this:

// Markup:
// <a class="button {{modifier_class}}">{{modifier_description}}</a>
//
// .is-active - Highlight the button when active.

will output:

`<a class="button is-active">Highlight the button when active.</a>
`

Thanks you!

**Comment by JohnAlbin** [comment]
The modifier's description is already printed just above the modifier. Placing the description _inside_ the modifier is fairly redundant; I wouldn't consider this to be a useful feature for most people.

As for how you would do it, it's fairly big change to do. You'd have to fork the handlebars builder and then modify the variables passed to the Handlebars templates to add modifier_description, but only in the context of individual modifiers, not just per section. It would be a lot of work for very little pay off, IMO.
