### ISSUE TITLE
Google resizer integration

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#291]
Google resizer is a very friendly tool that may be useful for many people. We should consider adding a link to it that will open the current section in the resizer.

http://design.google.com/resizer/

**Comment by jnowland** [comment]
The same can be achieved with Chrome dev tools using `:fullscreen` and the devices drop down.

![fullscreen-api](https://cloud.githubusercontent.com/assets/1244314/14587247/563d76d4-04f3-11e6-8c6c-6828ad68ea0e.gif)

Functionality from: https://github.com/kss-node/kss-node/pull/294

**Comment by JohnAlbin** [comment]
> The same can be achieved with Chrome dev tools using :fullscreen and the devices drop down.

Agreed.

Also, I can't get the latest version of the Resizer to load local-DNS-resolved web sites.
