### ISSUE TITLE
Print out Variables in the KSS comment section

### ISSUE THREAD

**Issue by digitaldonkey** [kss-node/kss-node#301]
I wander how I can make my living Styleguide more alive. 

For example i want to define and document my font-families only in one place. But currently I use somenthing like: 

```
$base-font-arabic : Tahoma, Arial, sans-serif;

//
// Font Families
//
// <p><strong>$base-font-arabic : Tahoma, Arial, sans-serif;</strong></p>
//
// Styleguide Variables - Fonts - Font-Families
//

```

In SASS there is a way to print comments with #{$var}, but this function is only intended to write /* ... */ comments including variables. It would be great to have tho following working, but it dosn't work as intendet, but render literally.

```
//
// Font Families
//
// <p><strong>$base-font-arabic : #{$base-font-arabic};</strong></p>
//
// Styleguide Variables - Fonts - Font-Families
//

```

I hope I made my intentions clear. Any suggestions how to archive this or simillar

**Comment by JohnAlbin** [comment]
Duplicate of #50
