### ISSUE TITLE
"--template " argument doesn't exist?

### ISSUE THREAD

**Issue by param-randhawa** [kss-node/kss-node#302]
Am I doing something wrong? The "--template " argument doesn't seem to be working any more. How do I specify a custom template?

**Comment by JohnAlbin** [comment]
`kss-node --help`

Or the docs on the homepageg. https://github.com/kss-node/kss-node#using-the-command-line-tool

**Comment by param-randhawa** [comment]
@JohnAlbin Thanks for your reply! I already tried using kss-node --help but unfortunately the --template option doesn't come up in help. I am using "kss@3.0.0-beta.4" I hope this makes sense. I am trying to apply a custom template to the default style guide template. Thanks in advance for all your help! Cheers!

**Comment by JohnAlbin** [comment]
I was suggesting that you *read* the docs instead of scanning for the `--template` option which was replaced with `--builder`.

Custom templates made for kss-node 2 won't work for kss-node 3 as the API is completely different. You could port them to the new API, but I don't have a guide for how to do that.

**Comment by param-randhawa** [comment]
@JohnAlbin Thanks for your quick reply again! I was looking into "..\\..\\AppData\\Roaming\\npm\\node_modules\\kss\\builder\\handlebars" folder and copied the default "builder" folder into my styleguide project folder (which I will customize later), but when I build it I get the following error "Error: kss-node expected the builder to implement KssBuilderBase API version 3.0; version "3.0"  is being used instead."

**Comment by JohnAlbin** [comment]
You should use the `--clone` option when you create a new custom builder.

Please open a new issue if you experience bugs.
