### ISSUE TITLE
Twig.js throws error when using kss in "watch" task

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#305]
When using a gulp watch task, the Node.js environment stays open which means the Twig.js module's global variable stays alive across all builds.

And Twig.js throws an error when KSS tries to re-build the style guide because it re-registers the templates.

We need to zero-out the Twig.js global object when the builder is initialized.

This is a familiar problem because I was seeing these same problems in our mocha tests which has a similarly long-running Node.js process.

**Comment by jedihe** [comment]
I'm seeing this problem with kss 3.0.1; a custom watch task was frequently hard stopped with message:

```
TwigException: There is already a template with the ID abc.html.twig
```

After finding https://github.com/twigjs/twig.js/issues/414#issuecomment-287342662, I tried it:

```
const Twig = require('twig');
const KalaStatic = require('kalastatic');
// ... build custom kalastatic configuration (nconf)
const kstat = new KalaStatic(nconf);

// ...

// Clear the Twig cache right before calling kalastatic.build().
Twig.cache();

kstat.build().then(() => {
  // Success
}).catch((err) => {
  // Error
});
```

Which fixed the problem for me.
