### ISSUE TITLE
Unknown arguments: template, helpers

### ISSUE THREAD

**Issue by mariohernandez** [kss-node/kss-node#309]
After upgrading to v 3.0.0-beta-5 I am no longer able to compile my style guide components.  I keep getting this error:
```Unknown arguments: template, helpers (Unknown arguments: template, helpers
[12:15:59] 'styleguide' errored after 369 ms
[12:15:59] Error: Command `kss-node --source sass --destination styleguide/dist/default --template styleguide/templates/style-guide --helpers styleguide/helpers --css ../../../css/visit-the-usa.main.css --js ../../../js/dist/all.js` failed with exit code 1```

I am able to get around it by changing "template" to "builder" and ignoring the helpers, but would like to be able to have thing working as before.
Thanks in advance for any help.

**Comment by param-randhawa** [comment]
@mariohernandez see this https://github.com/kss-node/kss-node/issues/302

**Comment by param-randhawa** [comment]
also see this https://github.com/kss-node/kss-node/issues/307

**Comment by JohnAlbin** [comment]
Thanks, @param-randhawa! I appreciate you helping out in the queue. I apologize for being snappish in our earlier conversations.

Also, @mariohernandez, if you want to continue using kss-node 2.x, it is still supported. But if you want to use 3.x, you'll have to port your custom 2.x template to the new variables found in the default 3.x builder.

**Comment by mariohernandez** [comment]
Thank you John.
