### ISSUE TITLE
Upgrade to twig.js 0.9.6 that fixes "npm WARN deprecated" during install

### ISSUE THREAD

**Issue by digitaldonkey** [kss-node/kss-node#326]
```
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. 

npm ls graceful-fs

[...]
└─┬ kss@3.0.0-beta.14
  └─┬ twig@0.9.5
    └─┬ phpjs@1.3.2
      ├─┬ glob@3.2.1
      │ └── graceful-fs@1.2.3
      └─┬ mocha@1.17.0
        └─┬ glob@3.2.3
          └── graceful-fs@2.0.3

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

npm ls jade
[...]
└─┬ kss@3.0.0-beta.14
  └─┬ twig@0.9.5
    └─┬ phpjs@1.3.2
      └─┬ mocha@1.17.0
        └── jade@0.26.3
```

https://github.com/isaacs/node-glob/tree/v7.0.3
--> I guess [phpjs@1.3.2](https://www.npmjs.com/package/phpjs) would need to be updated or replaced. 
https://www.npmjs.com/package/pug

**Comment by digitaldonkey** [comment]
Submitted Issue in phpjs
[npm WARN deprecated while installing phpjs](https://github.com/kvz/locutus/issues/294) (https://github.com/kvz/locutus/issues/294)

**Comment by JohnAlbin** [comment]
```
[...]
└─┬ kss@3.0.0-beta.14
  └─┬ twig@0.9.5
    └─┬ phpjs@1.3.2
      ├─┬ glob@3.2.1
      │ └── graceful-fs@1.2.3
      └─┬ mocha@1.17.0
```

Wait. What? phpjs installs mocha as a dependency!?!? That's so wrong.

**Comment by JohnAlbin** [comment]
Here's the PR that replaces phpjs in Twig.js https://github.com/twigjs/twig.js/pull/376

**Comment by digitaldonkey** [comment]
Is this allready commited somewhere?

**Comment by JohnAlbin** [comment]
The upstream fix has been committed, but Twig.js 0.9.6 has not yet been released. https://github.com/twigjs/twig.js/releases

**Comment by JohnAlbin** [comment]
Twig 0.10.x was released and we've merged that into kss-node's package.json.
