### ISSUE TITLE
Write files only if changed?

### ISSUE THREAD

**Issue by digitaldonkey** [kss-node/kss-node#328]
While implementing KSS with browser-sync I want to avoid reloading html-files if only my css changed (No kss komments changed -> in theory the generated HTML files should be the same).

But when I add a watch task for the html files to decide if I need to trigger browser-sync reload  it seems that the kss run is always regenerating all the files. 

Or is there any other way to to decide on a gulp-level if reloading is required or not?

**Comment by bm2u** [comment]
@digitaldonkey you have several options to optimize reload behavior of browser-sync. Please refer to https://www.browsersync.io/docs/gulp/ for further details.

I solved it for my workflow as follows. Reload manually or as a seperate gulp task. With these two ways of reloading you should do the trick.

```
// require modules
//-------------------------------------------------
var gulp   = require('gulp'),
    browserSync = require('browser-sync').create(),
    runSequence = require('run-sequence').use(gulp),
    bsconfig = require('../../config').browsersync,

// watcher task
//-------------------------------------------------
gulp.task('watch', ['build'], function() {
 	
	// create browsersync instance
 	browserSync.init(bsconfig.development, function () {
	    
	    // run certain task after changes
	    gulp.watch(config.styleguide.docs, ['watch:styleguide']);

	    // reload manually from watch task
	    gulp.watch(config.styleguide.templates.docs, ['styleguide', browserSync.reload]);
	});
});

// browser-sync reload task for serial tasks (run-sequence)
//-------------------------------------------------
gulp.task('bs:reload', function() {
    browserSync.reload();
});

// reload via gulp task after styleguide build
//-------------------------------------------------
gulp.task('watch:styleguide', function(callback) {
    runSequence(
			'styleguide',
			'bs:reload',
        callback);
});
```
Hope that helps..

**Comment by digitaldonkey** [comment]
Actually I think you misunderstood my question. I run kss about the same way. 

A reload is only required when the Doc section changes. For performance reasons I don't wanna reload HTML if it didn't actually change. So the best would be if KSS only writes new files if they are differing from the last version or return the path of the files actually changed.

**Comment by bm2u** [comment]
oh ok - got you. Sorry for miss-understanding.

**Comment by digitaldonkey** [comment]
I learned kss returns a promise.
Is there any way to get a list of the generated files? 
Or even better a list of the actually newly generated and changed files?

**Comment by digitaldonkey** [comment]
OK. I think I got my Issue fixed with this.

Found a way to tackler only changed files using gulp-cache, but browserSync seems not to support selective reloading of HTML files and **reloads full page anyhow.**

So the following is to show my approach, but any non-matching page will reload too.

```
gulp.watch(conf.styleguide.destination + '/**/*.html')
  .on('change', function(event) {
    plug.gutil.log('#styleguide_watcher  ' + event.path + ' was ' + event.type);
    var filename = event.path.replace(/^.*[\\\/]/, '');
  	  gulp.src(event.path)
	  .pipe(plug.cached(event.path, {optimizeMemory: true}))
	  // Using gulp-debug to verify what really changed.
	  .pipe(plug.debug({title: 'Change detected at ' + filename}))
	  plug.bs.stream({match: '**/' + filename});
});

```
