### ISSUE TITLE
Markdown in Documentation

### ISSUE THREAD

**Issue by lukas293** [kss-node/kss-node#329]
It would be great to have the ability to use markdown in your kss-documentation. Should be not to hard to implement, just let a markdown-parser like marked process the descriptions output

**Comment by hsnaydd** [comment]
+1

**Comment by matthewferry** [comment]
You should be able to write markdown in the description area if you're following the KSS comment syntax. 

```
/*
  Baz

  ## Some description header

  - List
  - of
  - things

  Descriptions can keep going.
  
  Markup:
  <div class="baz {{modifier_class}}"></div>

  Style guide Foo - Bar - Baz
*/
```
KSS builds this as:
```
{ header: 'Baz',
  description: '<h2 id="some-description-header">Some description header</h2>\n<ul>\n<li>List</li>\n<li>of</li>\n<li>things</li>\n</ul>\n<p>Descriptions can keep going.</p>\n',
  deprecated: false,
  experimental: false,
  reference: 'Foo - Bar - Baz',
  referenceNumber: '1.2.3',
  referenceURI: '',
  weight: 0,
  markup: ' <div class="baz {{modifier_class}}"></div>',
  modifiers: [ ],
  parameters: []
  ...etc...
}
```

Or am I misunderstanding the question?

**Comment by hsnaydd** [comment]
Yes we can write markdown inline but It would be very nice if we could give a reference md file as description.

**Comment by ryuran** [comment]
You can add a kss custom field with path to your markdown.
`// Documentation : mydoc.md`
And a handlebars helper to read the markdown file in your custom template.

**Comment by amaschas** [comment]
From what I can tell, the only section that can take a path as an argument is markdown. Would the handlebars helper have to load the file and compile the markdown in that case? It might be better to just have the build process recognize the reference to a path for any section. Seems like a pretty straightforward change, if I'm understanding the code correctly.

**Comment by JohnAlbin** [comment]
> From what I can tell, the only field that can take a path as an argument is markdown. Would the handlebars helper have to load the file and compile the markdown in that case? 

Yep.

> You'd need a way to iterate over the fields

Nope. If you have custom fields, you'll need a custom builder that outputs those fields. Iterating over fields would make it impossible to output the needed wrapper markup per field.

> It would be very nice if we could give a reference md file as description. 

The core principle of KSS is to put the docs as close to CSS source as possible, with the thinking that if you update/write CSS you're more likely to write docs if it is all together. Separating the docs seems counter-productive to me.
