### ISSUE TITLE
Expand to Fullscreen Component

### ISSUE THREAD

**Issue by RobLoach** [kss-node/kss-node#333]
When clicking the "Expand" button, it opens a new window, with just the component and CSS on the page, allowing for Full Screen previews on the components on their own.

**Comment by thiagodemellobueno** [comment]
I dig.

Earlier today I was thinking about how we could test using kalastatic, for some presos (and make them supersweet thusly). This makes that easier!

**Comment by RobLoach** [comment]
Definitely, I would find this particularly helpful when demonstrating layouts, and maybe even compiling multiple atoms/molecules/components together for large demos.

**Comment by JohnAlbin** [comment]
Duplicate of #165
