### ISSUE TITLE
Locally installed KSS does not work, get an error

### ISSUE THREAD

**Issue by vortex6688** [kss-node/kss-node#334]
Locally installed KSS doesn't work, get an error after i use this: "./node_modules/.bin/kss --help" in a command line, the error looks like this:
"Error: kss expected the builder to implement KssBuilderBase API version 3.0; version "3.0" is being used instead.", 

When i installed it globally though, and used: "kss --help" it worked just fine, no errors, generating styleguide with no issues, but again... if i use --clone to create a separate builder that i could customize locally (for each project, since it's installed globally), it creates builder folder, but when i use --builder option to use a new builder folder that i cloned for customization, it throws : " Error: kss expected the builder to implement KssBuilderBase API version 3.0; version "3.0" is being used instead." just as well...

So... can't find any solution so far... could someone give me a hint how to fix it please? 

 Thank you!

**Comment by vortex6688** [comment]
Ok never mind, i fixed it, please close this issue, my apology for the inconvenience.

**Comment by RobLoach** [comment]
:+1:
