### ISSUE TITLE
Quickstart guide uses deprecated kss-node command

### ISSUE THREAD

**Issue by renestalder** [kss-node/kss-node#336]
This might have a specific reason, so I ask first before making any pull request.

In the quick start guide, the examples show how to use the command line with `kss-node`. The readme differs from this, showing examples with `kss` which might not work.

**Comment by ryuran** [comment]
`kss-node` command was recently renamed to `kss`
https://github.com/kss-node/kss-node/issues/310

**Comment by renestalder** [comment]
So the quickstart guide wasn't updated.

**Comment by renestalder** [comment]
I updated the quickstart guide to work with both versions.
