### ISSUE TITLE
How to add a handlebars helper or twig function for kss-builder ? (3.x.x)

### ISSUE THREAD

**Issue by ryuran** [kss-node/kss-node#337]
Hello!

I need some documentation about kss builder and how to build :
 - a custom one,
 - with custom fields,
 - with custom helpers
 - in twig and handlebars both
 
It's for make a builder with color,  font and svg demo.

**Comment by RobLoach** [comment]
`--builder=<path/to/builder>`

Have a look through kss/builder for some demos... You can reference `markup: component.twig` in your KSS docs.

**Comment by ryuran** [comment]
It's ok to choose twig builder instead of handlebars.
It's ok to use a twig template as markup in kss doc comments.

My questions are:
- "How to had a twig function in the custom twig builder ?"
- "How to had a handlebars helper in the custom handlebars builder ?"

**Comment by nzjames** [comment]
`helpers` parameter/property was renamed to `extend` as per https://github.com/kss-node/kss-node/issues/295. It works via CLI `--extend` or `"extend": "./kss/helpers",` in your `kss-config.json`.

**Comment by ryuran** [comment]
Ans it works thé samz way for twig fonctions ?

**Comment by ryuran** [comment]
And it works the same way for twig functions ?

**Comment by ryuran** [comment]
I tested --extend option with this handlebars helper: 
https://github.com/cleverage/garden-starter-kit/blob/master/.gsk/kss/helpers/kssColors.js

In #295 @JohnAlbin say:
> simplify the interface for modules loaded by the option (i.e. export the module's function directly instead of through the module.exports.register name.)

So I don't know how to write my helper.

It seems to be the standard way `handlebars-helper-compose` by exemple : https://github.com/helpers/handlebars-helper-compose/blob/master/index.js

**Comment by ryuran** [comment]
https://github.com/kss-node/kss-node/wiki/Using-the-default-Handlebars-template Is not up to date.

**Comment by ryuran** [comment]
I found the way for my helpers.
Only remove `.register` seems work

Need to do same work for twig tag.

**Comment by ryuran** [comment]
I did it : 

twig taghttps://github.com/cleverage/garden-starter-kit/blob/master/.gsk/kss/extend/twig/kssColors.js

hbs helper: https://github.com/cleverage/garden-starter-kit/blob/master/.gsk/kss/extend/handlebars/kssColors.js

**Comment by RobLoach** [comment]
@ryuran Could you shoot something up to the Wiki, or a PR for documentation on how you accomplished this?

**Comment by ryuran** [comment]
Yes

**Comment by RobLoach** [comment]
Thanks a lot! Am interested to see how it was all done :+1:

**Comment by ryuran** [comment]
https://github.com/kss-node/kss-node/wiki/Extend-template-for-a-custom-block @RobLoach ok for you ?

I think to put this helpers on github.
I have one for font-icon and one for colors, in twig and handlebars
