### ISSUE TITLE
Map source annotation to source files

### ISSUE THREAD

**Issue by renestalder** [kss-node/kss-node#339]
Right below the code in the styleguide appears a line to point to the original source file, e.g. "Source: components/index.css, line 1". Since I deliver the styleguides on a minified build, there's only one line. Would it be possible to map this to the `source` folder files instead the compiled CSS file?

**Comment by JohnAlbin** [comment]
When you build the style guide with kss-node, you choose which source directory to use. I never use the compiled CSS as my source; I always use my Sass folder as the kss source.
