### ISSUE TITLE
Unique id/for in html elements

### ISSUE THREAD

**Issue by patrickmichalina** [kss-node/kss-node#346]
Is there currently a way to have ids be created randomly to allow multiple input (with different styles) be displayed on the page and still work. What is happening for me is after the default style is applied, the other styles are using the same template (and the same if/for attribute values) making the other inputs unusable. Any techniques to fix this? I'd appreciate some guidance here. Thanks

**Comment by JohnAlbin** [comment]
I don't understand the issue; you're going to have to describe the problem in more detail.

**Comment by ryuran** [comment]
If you make a form in KSS markup with an ID
```
<div class="field {{ modifier_class }}">
    <label for="inputId">Label</label>
    <input type="text" id="inputId" />
</div>
```

For each variant (modifier) the same html with same ID is ducplicated.
So we have multiple ID in result kss page. 😿 

We need a variable to do an unique prefix or postfix ID by rending of markup.

**Comment by zhawkins** [comment]
I've used the `{{ modifier_class }}` to generate specific modifier IDs. 
```
<div class="field {{ modifier_class }}">
    <label for="inputId-{{ modifier_class }}">Label</label>
    <input type="text" id="inputId-{{ modifier_class }}" />
</div>
```
Kinda wonky, but it seems to work.

**Comment by ryuran** [comment]
Yes but i use same twig file for KSS markup and in my project…
So, in this case, this can't be the solution.

**Comment by patrickmichalina** [comment]
An example would be the same set of radio button groups but with different templates
