### ISSUE TITLE
graceful-fs@2 and @3 support will be removed soon

### ISSUE THREAD

**Issue by ChALkeR** [kss-node/kss-node#347]
Hi. `kss` is currently `#29` in my [list of modules](https://gist.github.com/ChALkeR/d39b49642e02277d2292d66c2ea0bced) that would likely to be broken when https://github.com/nodejs/node/pull/6413 lands (which is anticipated to happen before v7.0).

Note that `graceful-fs@1` and `graceful-fs@4` are ok and would not be broken by this, but a `require()` on `graceful-fs@2` or `graceful-fs@3` would cause an error soon.

That is, runtime warning `fs: re-evaluating native module sources is not supported.` would be turned into a throw.

If you or your deps use `graceful-fs@2` or `graceful-fs@3` in runtime — you are affected. 

Tracking: https://github.com/nodejs/node/issues/5213.
Related: #326.

/cc @JohnAlbin @RobLoach.

**Comment by JohnAlbin** [comment]
kss-node never required graceful-fs directly; it was a dependency of a dependency.

I've just reinstalled kss-node 3.0.0-beta.15 and it installs graceful-fs 4, so it looks like the upstream dependency fixed this.

I just checked kss-node@2 and it also installs graceful-fs 4.

Closing.

Thanks for the heads up!
