### ISSUE TITLE
PostCSS custom build

### ISSUE THREAD

**Issue by toomuchdesign** [kss-node/kss-node#348]
Is it possible to set up kss-node to build the stylesheets using a user-defined stack of custom PostCSS plugins?

**Comment by RobLoach** [comment]
:+1:

**Comment by toomuchdesign** [comment]
Thank you Rob. I don't know JSTransformers but, it sounds interesting. I'll read some doc as soon as I can.

Since there isn't an integrated way to plug CSS postprocessors, I'll just try to setup a project which wraps kss-node and my PostCSS compilation routine and run both in succession.

I'll keep you updated on the results!

Cheers!

**Comment by toomuchdesign** [comment]
Well, It worked somehow! I set up a build script to fire 2 separate processes:
- kss-node markup generation
- postcss compilation starting from a custom bootstrap @import file

Not elegant but, but effective!

Of course, It'd be nice to be able to plug a custom postCSS stack to the CSS files collected by kss-node process.
