### ISSUE TITLE
homepage content never parsed

### ISSUE THREAD

**Issue by rootwork** [kss-node/kss-node#349]
Great project -- I've used it in the past and am getting to do so again for a current project.

However, I'm finding with 3.0.0-beta.14 that the homepage content is never parsed -- regardless of what or where the homepage content is, or what contents it has, kss-node always returns this error:

`WARNING: no homepage content found in [filename].`

Details:

* node v5.10.0
* npm 3.10.2
* kss-node 3.0.0-beta.14

Steps to reproduce, from a blank project with node initialized:

1. `npm install --save-dev kss`
2. `mkdir sass`
3. `touch sass/style.scss`
4. (Put some KSS documentation in `style.scss`.)
5. `touch homepage.md`
6. (Put some Markdown in `homepage.md`.)
7. `npm-exec --source sass` or `./node_modules/.bin/kss --source sass`

Result:

`WARNING: no homepage content found in homepage.md.`
`Style guide build completed successfully!`

So to be clear, it is building the styleguide (which is great) but it's not parsing the homepage, so the "overview" page in the styleguide is blank. I've tried it with other filenames (such as `styleguide.md`, specified in the build), I've tried it with varying amounts of Markdown, I've tried it with straight HTML. Nothin'.

Let me know if there's more information I can provide to track down this bug. Really love KSS-node otherwise!

**Comment by russpitre** [comment]
I'm seeing the same behavior as well.

**Comment by tlinkner** [comment]
Me too.

**Comment by bookwyrm** [comment]
`homepage.md` needs to be in your source directory. So if your source directory is `sass/` then you need to create `sass/homepage.md`

**Comment by tlinkner** [comment]
Thanks so much. That was the problem.

**Comment by rootwork** [comment]
Yes, thanks! That does address it.

Seems like this should be stated explicitly in the documentation. Should I open a new issue for that or can we repurpose this issue for updating the docs?

**Comment by bookwyrm** [comment]
It is noted in the [Differences from kneath/kss](https://github.com/kss-node/kss-node#differences-from-kneathkss) just not called out in the [CLI docs](https://github.com/kss-node/kss-node#using-the-command-line-tool).

**Comment by JordyPouw** [comment]
If you want to place it somewhere else, just do: `"../kss_styleguide/kss-homepage.md"`.

**Comment by JohnAlbin** [comment]
Fixed!

**Comment by JohnAlbin** [comment]
Thanks, @bookwyrm, for pointing out the docs; both where the docs were useful and where they were lacking.

**Comment by LukyVj** [comment]
Would be nice to document it better :) 
The comment of @JordyPouw helped me a lot :)

**Comment by wilkie** [comment]
It is mentioned that it is noted in [Differences from kneath/kss](https://github.com/kss-node/kss-node#differences-from-kneathkss), but that says:

> The file path must be relative to config file or working directory if given by command line. Just name it homepage.md and put it in directory of config file.

But, it seems it is actually relative to the "source" directory, not the config file. Am I mistaken?

**Comment by ryuran** [comment]
@wilkie are you sure to refer to the documentation of your current version?

This quote is related to recent change not y et released. 

Currently homepage file path is related to sources directory. It will change in next beta because it will be possible to have multiple sources.

**Comment by JackHowa** [comment]
Huh weird tried @bookwyrm idea: 

> homepage.md needs to be in your source directory. So if your source directory is sass/ then you need to create sass/homepage.md

Have scss/homepage.md

**Comment by dtarvin** [comment]
I have mine in my source directory (css) but I still get the warning.

**Comment by benmezasd** [comment]
I put homepage.md at the root of the project and it worked. Not sure if that's intended

**Comment by n-freman** [comment]
> I put homepage.md at the root of the project and it worked. Not sure if that's intended

Also worked for me
