### ISSUE TITLE
Error when scrolling: Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#362]
Tracks https://github.com/makotot/scrollspy/issues/8

**Comment by Aeotrin** [comment]
@JohnAlbin Found a solution to the non-stop console errors. When the fullscreen  functionality was added an ID was changed but the url that referenced that ID was not.

**Comment by JohnAlbin** [comment]
@Aeotrin Indeed! You are correct. Thanks for checking this!

**Comment by JohnAlbin** [comment]
Converting this bug report into a feature request to update to Scrollspy v0.1.3.

**Comment by JohnAlbin** [comment]
I also updated to Scrollspy v0.1.3.

**Comment by Aeotrin** [comment]
A different variant of this error occurs still
```scrollspy.js:111 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null(…)```

The change made in 3988c85 should instead be:
```
 <a id="kssref-{{ section.referenceURI }}"></a>
```
referenceURI does not exist, it is a attribute on the section variable.
