### ISSUE TITLE
Provide Markup Template Variables

### ISSUE THREAD

**Issue by RobLoach** [kss-node/kss-node#369]
When writing a KSS definition, you can give it the `Markup:` template:

``` button.css
/*
Button

A clickable button.

Markup: button.twig

Styleguide: button
*/
```

``` button.twig
<button class="{{ style }}">{{ title }}</button>
```

It would be great if you could provide some dummy variables fro the template to use in the styleguide.

``` button.scss
/*
Button

A clickable button.

Markup: button.twig

Variables:
  title: My Button Example
  style: large

Styleguide: button
*/
```

Or a JSON array, rather then YAML, or something. There is a workaround to use a styleguide template example and inject the variables, but it would be nice if KSS did this for us.

**Comment by soniktrooth** [comment]
++ this would be super helpful

**Comment by ryuran** [comment]
json file are not enough ?

**Comment by thiagodemellobueno** [comment]
@ryuran can you elaborate?
Is it a single json file for globals or is it at component level?

**Comment by ryuran** [comment]
If you name a file `component.json` in the same directory as your component template `component.twig`, this json will be used as data source in the template.

@thiagodemellobueno

**Comment by thiagodemellobueno** [comment]
Well that's super lovely. @RobLoach that satisfy's the use case yes?

**Comment by RobLoach** [comment]
Whoa! Didn't know that "just worked" :tm: . Nicely done, @ryuran. :+1:

**Comment by ryuran** [comment]
Maybe some doc needed. This feature deserves to be known.

**Comment by soniktrooth** [comment]
This is amazing. Thanks for he heads up @ryuran

**Comment by Nodles** [comment]
Thanks! This solve our problem

**Comment by thiagodemellobueno** [comment]
@ryuran — a follow up question: is there a "general son file" outside of kss-config.json (which doesn't seem to make those variables available to the templates) which all templates would have access to? 
eg. css-globals.json or something?

**Comment by ryuran** [comment]
Currently there are not "general json file".

I'm not sure why you could need it.
Kss is made to separate each css component. So, have something too much common is not in this philosophy.

**Comment by jameelmoses** [comment]
I agree with @thiagodemellobueno. I use a `twig-data.json` file globally for all of my twig data during development. My projects are structured in a way that all twig partials are together, scss partials are together, etc. For projects like this, it doesn't make sense to have a bunch of `.json` files in the same directory. Does anyone know of a way to make a single `.json` file accessible to the styleguide?

**Comment by jameelmoses** [comment]
@ryuran any thoughts on the above?

**Comment by ryuran** [comment]
@jameelmoses If you build your project by this way, it seems to be legit.

I do not feel comfortable with the idea of a style guide changing relatively to project data. I always make component (css+twig+json) to be easily moved to an other project.

It’s not the same usage of KSS.
