### ISSUE TITLE
npm-exec

### ISSUE THREAD

**Issue by mkastner** [kss-node/kss-node#370]
The kss "Quick Start Guide" recommends using npm-exec in the "Running kss-node repeatedly" section.

However the npm-exec documentation says:

npm-exec
Execute commands in the context of an npm package
**_Warning this is just getting started, but is already somewhat usable._**

Somewhat usable? Seriously? Is that really the recommended tool?

I know, this ain't the problem of kss-node but just wanted to let you know that npm-exec breaks on installation on macOS Sierra (here's just on off a multitude of compilation errors):

```
/my/path/.node-gyp/7.2.0/include/node/v8.h:230:5: error: assigning to 'v8::Object *volatile' from incompatible
      type 'v8::Value *'
```

**Comment by JohnAlbin** [comment]
> However the npm-exec documentation says:

Can you point to the part of the kss-node documentation that made you believe that we recommend that you should use npm-exec? If the page at https://github.com/kss-node/kss-node/wiki/npm-quick-start-guide isn't clear, we should make it clearer.

**Comment by mkastner** [comment]
I apologize. I should have pointed to the respective documentation:

[https://github.com/kss-node/kss-node/wiki/Quick-Start-Guide#installing-kss-node](https://github.com/kss-node/kss-node/wiki/Quick-Start-Guide#installing-kss-node)

**Comment by JohnAlbin** [comment]
doh! Thanks for pointing out the error. I've fixed it now.
