### ISSUE TITLE
Twig spaceless is not working

### ISSUE THREAD

**Issue by lauriii** [kss-node/kss-node#373]
Twig spaceless block is not working as expected. For some reason if I use the spaceless the markup will get escaped. More info about spaceless: http://twig.sensiolabs.org/doc/tags/spaceless.html

### How to reproduce
Create template:
```
{% spaceless %}
  <div>
    test
  </div>
{% endspaceless %}
```

And it should output:
```
&amp;lt;div&amp;gt;
    test
  &amp;lt;/div&amp;gt;
```

**Comment by JohnAlbin** [comment]
I totally forgot I reported this upstream already. https://github.com/twigjs/twig.js/issues/372

We should track that issue here.

**Comment by ryuran** [comment]
Will be fixed at next twig.js release

**Comment by thamas** [comment]
#397 is merged. So it may be closed…(?)

**Comment by ryuran** [comment]
@thamas yes, it should. @JohnAlbin
