### ISSUE TITLE
Anchor tags not working in Twig builder

### ISSUE THREAD

**Issue by iampuma** [kss-node/kss-node#375]
Currently on the master branch the hashtags links are not working in the side menu.

I suppose the problem is due to the new scrollspy.js?

Chrome console output:
```
  Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
```

Great work on kss-node!

**Comment by JohnAlbin** [comment]
Hmm… I've seen that error (thrown by new scrollspy.js), but I thought I fixed it.

The demo is using the latest master as well and I'm not seeing that error. http://kss-node.github.io/kss-node/section-demo.html

Can you give more details about what options you are using? And I just pushed more commits in the last hour; can you update and see if it still happens?

**Comment by iampuma** [comment]
@JohnAlbin it looks like  ` --builder builder/twig` option is breaking the anchor tags on my styleguide.

**Comment by JohnAlbin** [comment]
> it looks like --builder builder/twig option is breaking the anchor tags on my styleguide.

Confirmed! Thanks for the information.

I'll fix it today.

**Comment by iampuma** [comment]
Confirmed working, thanks.
