### ISSUE TITLE
Show "source (hbs/twig) and markup (html) and data (json)" in doc

### ISSUE THREAD

**Issue by ryuran** [kss-node/kss-node#377]
Hello

It can be great if we can show Twig original source, final markup html and data.

# Show twig
Devs prefer read twig, if a component include an other the include tag is present.
They can see where is variables, loop and conditions.

# Show data
Devs need to know data format (example) to feed the template.

This could be some tabs/panel.

**Comment by JohnAlbin** [comment]
The "show twig" part of this request is already fixed with https://github.com/kss-node/kss-node/issues/322

> Devs need to know data format (example) to feed the template.

I completely agree with this, but showing the sample data from the [template].json file is not sufficient. I usually put the actual data requirements as comments in the twig file.

**Comment by ryuran** [comment]
Good news! I missed this option.
Yes, comment of twig files is better than the json.

I close this issue.
