### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by mkastner** [kss-node/kss-node#380]
First of all: thanks for the great tool. Its' awesome.

Nevertheless, I have problems using the api. In the documentation here

[http://kss-node.github.io/kss-node/api/master/module-kss.html](http://kss-node.github.io/kss-node/api/master/module-kss.html)

it says: _The usual style guide build process:_

and then build process is being described.

My first question: the steps described in this process, are they being invoked by the kss-function or do some or all of these steps need to be invoked by the program which called the kss-function in the first place?

I've been reading the cli source back and forth because I thought it could would be able to understand how it makes use of the API but I still don't have a clue, how to properly genearate a document.

I was able to create documents by running kss and then use the resulting styleguide object by passing it on to my own handlebars process.

However that seems kind of clumsy. I am wondering if it's possible make use of kss's built in handlebars builder?

Or - if such a thing exists: could anyone point me to an example using the kss-node API?

Any help is greatly appreciated.

**Comment by mkastner** [comment]
Sorry, I was totally off track. Mea Culpa!

**Comment by sebastianserna** [comment]
I want to report an issue here, where can I find the API documentation? current links are broken:
http://kss-node.github.io/kss-node/section-javascript-api.html
