### ISSUE TITLE
Drupal 8 Filters: Use the twig-drupal-filters Package

### ISSUE THREAD

**Issue by RobLoach** [kss-node/kss-node#384]
Will help clean up the source....
https://www.npmjs.com/package/twig-drupal-filters

**Comment by Kingdutch** [comment]
Could we tag beta19 that includes this change? We're using KSS in one of our Drupal projects and need this to compile :)

**Comment by RobLoach** [comment]
Thanks for checking this out @Kingdutch. Looks like there are a few commits that haven't been tagged yet. Do you know of any other PRs or fixes that we should get in before beta19 hits?

**Comment by Kingdutch** [comment]
I haven't found any open or closed PRs that are missing for us.
Looks like #288 is done. I currently jump through some hoops to add the Attributes object to every template. I'll open up a separate issue for that though (#451 was born after writing that sentence).
