### ISSUE TITLE
How do I execute/run kss from command line?

### ISSUE THREAD

**Issue by mkastner** [kss-node/kss-node#391]
I've installed kss (version 3.0.0-beta.17) but the only way I can get it to run is by directly calling the api like this:

```
const kss = require('kss'),
    kssConfig = require(path.resolve('config/kss-config.js'));

kss(kssConfig).then(styleGuide => {
    return styleGuide;
 });
```

Other than that, I can't get it to run. The command line (MacOS/iterm) simply does nothing. Here's what I've tried.

BTW, kss is installed as a project depdendency and _not_ globally. So I am trying everything from the project root.

kss is installed as devDependency version "3.0.0-beta.17".

So, the first thing I've tried:

`$ kss --demo
-bash: kss: command not found`

Ok, it's propably not in the path. So I explicitly add the path in the  command and also add the "node" command:

`$ node node_modules/kss/index.js --help`

Nothing happens. Then I try:

`$ node node_modules/kss/lib/cli.js --help`

Again, nothing happens.

I am running out of options.

**Comment by ryuran** [comment]
It's here : `./node_modules/.bin/kss`

Usually, developers put `./node_modules/.bin` in $PATH

**Comment by mkastner** [comment]
@ryuran

Wow, that's embarassing. I've been working with node for quite a while now, but I didn't know that module naming and mapping works via these links. Thanks for this information.
