### ISSUE TITLE
Custom builder kss.scss is not being processed

### ISSUE THREAD

**Issue by mkastner** [kss-node/kss-node#392]
I've created a custom builder via
`
kss --clone
`
and I have this config file "kss-config.js":

```
{
  "source": "/localpath/scss-files",
  "destination": "/localpath/css-files",
  "builder": "./custom-builder",
  "css": [
      "/asset-files/css/my-style-one.css",
      "/asset-files/css/my-style-two.css",
  ],
  "title": "My Style Guide"
}
```

In my 

`
/localpath/custom-builder/kss-assets/kss.scss
`
I have changed the some styles.

However when I regnerate the styleguide these changes are not being processed and do not appear in the target css.

**Comment by ryuran** [comment]
You have to run `npm install` and`npm run sass` in your builder directory to generate you `kss.css`files from your new `kss.scss`.

**Comment by mkastner** [comment]
@ryuran 

Thanks for your reply. I somewhat assumed something like that and I think your answer propably reflects the second step from the installation instruction on this project's homepage:

```
$ kss --clone custom-builder
$ kss path/to/sass styleguide --builder custom-builder
```

I would have tried it that way, but I don't know to which directory or file "styleguide" refers to. Since I was confused by that part of the documentation I thought, it might be outdated and in the meantime by some "magic" the sass processing would be part of custom builder anyway.

I did have node-sass in my node_modules already. But as I wrote, I thought it was part of build process. So ok, it's not and I have to explicitly call this step.

And there is no config option – either command line or in kss-config.json –, which I could set to invoke the scss-transpilation as part of the build process, right?

**Comment by ryuran** [comment]
`styleguide` refers to destination directory where your kss styleguide will be generated.

KSS do not transpile scss. You need to transpile your scss with node-sass.

You can create a script in your `package.json` to run transpilation and kss successively or use a task runner like gulp.

**Comment by mkastner** [comment]
I see. Thanks again. I think a pre-build job in package will do.
