### ISSUE TITLE
Document usage of {{modifiers}}

### ISSUE THREAD

**Issue by MartinMuzatko** [kss-node/kss-node#395]
While it is documented what modifiers are shown as in the markup, there is no information what to use for the css.

I see some are using {{modifier_class}}, some use {{$modifiers}}

Does it actually matter what the name is?

**Comment by RobLoach** [comment]
Likely from legacy changes. Are you using handlebars or twig?

**Comment by ryuran** [comment]
The variable name is the same for twig or handlebars in recent version. 
`{{ modifier_class }}`

**Comment by MartinMuzatko** [comment]
Default - I guess handlebars.

Thank you a lot for the quick response :)
