### ISSUE TITLE
Menu with more levels - <ul> for each depth

### ISSUE THREAD

**Issue by turolopezsanabria** [kss-node/kss-node#407]
Hello
I'm trying to hide all submenu items, and display them only if the parent is active.
The problem is that the menu has only `<li>` for all levels.
It would be great to have a structure like the one below, but I can't make it work:

<ul class="doc-nav">
<li><a class="link active" href="#">Title</a></li>
<li>
<ul class="doc-nav-sub-list">
<li>Section 1</li>
<li>Section 2</li>
<li>Section 3</li>
<ul>
<li>Section 3.1</li>
<li>Section 3.2</li>
<li>Section 3.3</li>
</ul>
<li>Section 4</li>
</ul>
</li>
</ul>

```
<ul class="doc-nav">
<li><a class="link active" href="#">Title</a></li>
<li>
<ul class="doc-nav-sub-list">
<li>Section 1</li>
<li>Section 2</li>
<li>Section 3</li>
<ul>
<li>Section 3.1</li>
<li>Section 3.2</li>
<li>Section 3.3</li>
</ul>
<li>Section 4</li>
</ul>
</li>
</ul>
```

**Instead of what I get right now:**

<ul class="doc-nav">
<li><a class="link active" href="#">Title</a></li>
<li>
<ul class="doc-nav-sub-list">
<li class="child">Section 1</li>
<li class="child">Section 2</li>
<li class="child">Section 3</li>
<li class="grandchild">Section 3.1</li>
<li class="grandchild">Section 3.2</li>
<li class="grandchild">Section 3.3</li>
<li class="child">Section 4</li>
</ul>
</li>
</ul>

```
<ul class="doc-nav">
<li><a class="link active" href="#">Title</a></li>
<li>
<ul class="doc-nav-sub-list">
<li class="child">Section 1</li>
<li class="child">Section 2</li>
<li class="child">Section 3</li>
<li class="grandchild">Section 3.1</li>
<li class="grandchild">Section 3.2</li>
<li class="grandchild">Section 3.3</li>
<li class="child">Section 4</li>
</ul>
</li>
</ul>
```

I've tried many things, including stuff like the one below, not working of course ;)
Can you help?

```
{{#each menu}}

{{#each children}}
<li>
{{header}}
{{#if grandchildren}}<ul>{{#each grandchildren}}<li>{{header}}</li>{{#each}}{{/if}}
</li>
{{#each}}

{{#each}}

```

**Comment by heissmusik** [comment]
I didn't build the entire KSS documentation that I was working on, but I did add on something similar and this code might help you. 

It looks like you are missing these two: `{{#if isActive}}` and  `{{#if children}}` 

I also used a Helper to detect "grandchildren" so these could be further indented with CSS. 

See below...

**index.hbs**
``` html         
{{#each menu}}
<li class="kss-nav__menu-item">
    <a class="kss-nav__menu-link" href="section-{{referenceURI}}.html">
        <span class="kss-nav__name">{{header}}</span>
    </a>
    {{#if isActive}}
    {{#if children}}
        <ul class="nav kss-nav__menu-child">
        {{#each children}}
            {{#isGrandChild referenceURI}}
                <li class="kss-nav__menu-item">
                    <a class="kss-nav__menu-link grand-child" href="section-{{../referenceURI}}.html#kssref-{{referenceURI}}">
                        <span class="kss-nav__name">{{header}}</span>
                    </a>
                </li>
            {{else}}
                <li class="kss-nav__menu-item">
                    <a class="kss-nav__menu-link" href="section-{{../referenceURI}}.html#kssref-{{referenceURI}}">
                        <span class="kss-nav__name">{{header}}</span>
                    </a>
                </li>
            {{/isGrandChild}}
        {{/each}}
        </ul>
    {{/if}}
    {{/if}}
</li>
{{/each}}
```

together with a HandleBars Helper in **builder.js**

```javascript
this.Handlebars.registerHelper('isGrandChild', function(refURI, options) {
    var fnTrue = options.fn, 
    fnFalse = options.inverse;

    return refURI.split('-').length > 2 ? fnTrue(this) : fnFalse(this);
});     
```

I hope this helps!

**Comment by turolopezsanabria** [comment]
Hello @heissmusik 
Thanks for the help! Unfortunately, it's not doing what I need. (list inside ul, wich is inside a list)
This is my current code (it's working as yours):

 ```
<ul>
    {{#each menu}}
      <li class="doc-nav-item {{#if isActive}}active{{/if}}">
        <a class="link" href="section-{{referenceURI}}.html">{{header}}</a>
        {{#if isActive}}
          {{#if children}}
            <ul class="doc-nav-sub-list">
            {{#each children}}
                <li class="doc-nav-item {{#if isGrandChild}}doc-nav-item-grand-child{{/if}}">
                {{header}}
                </li>
            {{/each}}
            </ul>
          {{/if}}
        {{/if}}
      </li>
    {{/each}}
    </ul>
```

Unfortunately, the output using either my solution or yours is a single list with classes  "doc-nav-item" and "doc-nav-item-grandchild", but I need <li class="doc-nav-item-grand-child"> to be inside a UL chlid of <li class="doc-nav-item">, and not at the same level.

I am getting this:

<ul>
  <li class="doc-nav-item">item 1</li>
  <li class="doc-nav-item">item 2
  <li class="doc-nav-item doc-nav-item-grandchild">item 2.1</li>
  <li class="doc-nav-item doc-nav-item-grandchild">item 2.2</li>
  <li class="doc-nav-item doc-nav-item-grandchild">item 2.3</li>
  </li>
</ul>

instead of 

<ul>
  <li class="doc-nav-item">item 1</li>
  <li class="doc-nav-item">item 2
    <ul>
      <li class="doc-nav-item doc-nav-item-grandchild">item 2.1</li>
      <li class="doc-nav-item doc-nav-item-grandchild">item 2.2</li>
      <li class="doc-nav-item doc-nav-item-grandchild">item 2.3</li>
    </ul>
  </li>
</ul>

**Comment by heissmusik** [comment]
Perhaps you must make sure that your source files have the right format?

```scss
// Some Element 
//
// Some element description
//
// Markup:
// <div class="class-name-here">
//      example text
// </div>
//
// Styleguide: 3.1.2
```

**Comment by turolopezsanabria** [comment]
hey @heissmusik 
no, still not working :)
I will try to do a different thing. Thanks anyway

**Comment by ajbrun** [comment]
Hi @turolopezsanabria,

I was having the same problem as you and I was quite surprised the menu didn't nest and follow standard ul/li nesting rules out of the box. I've made a few handlebar helpers, which I think have solved the problem, although having this functionality in the core code would be handy too.

I'm no handlebars expert and these functions haven't been put through their paces very much, but let me know if it helps:

The JS files can be added to a helpers directory referenced by the extend configuration option.

nested-menu.js - To create a main nested menu with ul/li hierarchy
```javascript
module.exports = (handlebars) => {
  handlebars.registerHelper('nestedMenu', (menu) => {

    // Flatten all objects to a single level (remove children)
    const flattenedMenu = [];

    for (let i = 0; i < menu.length; i += 1) {
      const menuItem = JSON.parse(JSON.stringify(menu[i]));
      const children = menuItem.children;
      delete menuItem.children;

      flattenedMenu.push(menuItem);

      for (let c = 0; c < children.length; c += 1) {
        flattenedMenu.push(children[c]);
      }
    }

    const nestedMenu = [];

    for (let i = 0; i < flattenedMenu.length; i += 1) {
      const parentItem = flattenedMenu[i];
      if (parentItem.depth > 1) {
        continue;
      }

      parentItem.children = getChildren(parentItem);
      nestedMenu.push(parentItem);
    }

    function getChildren(parentItem) {
      const children = [];
      for (let i = 0; i < flattenedMenu.length; i += 1) {
        const child = flattenedMenu[i];

        // It's the same item, so ignore
        if (child.referenceNumber === parentItem.referenceNumber) {
          continue;
        }

        // If it doesn't start with the reference number, then ignore
        if (child.referenceNumber.indexOf(parentItem.referenceNumber) !== 0) {
          continue;
        }

        // We've gone too deep
        if (child.depth > parentItem.depth + 1) {
          continue;
        }

        // We've reached a sibling level, so there aren't any more of these now
        if (child.depth === parentItem.depth) {
          break;
        }

        child.children = getChildren(child);
        children.push(child);
      }

      return children;
    }

    return nestedMenu;
  });
};
```

active-menu.js - To show only pages beneath the currently viewed page (I'm planning on using this for a side nav)
```javascript
module.exports = (handlebars) => {
  handlebars.registerHelper('activeMenu', (menu) => {
    const nestedMenu = handlebars.helpers.nestedMenu.apply(this, [menu]);

    function getActiveMenu(menuItems) {
      for (let i = 0; i < menuItems.length; i += 1) {
        const menuItem = menuItems[i];

        if (menuItem.isActive) {
          return menuItem;
        }

        const activeMenu = getActiveMenu(menuItem.children);

        if (activeMenu) {
          return activeMenu;
        }
      }

      return null;
    }

    return getActiveMenu(nestedMenu);
  });
};
```
Inline nav template (alter for your own uses):
```html
    {{#* inline "list-item"}}
      <li>
        <a href="item-{{referenceURI}}.html">
      {{header}}
      </a>
        {{#if children}}
          <ul>
            {{> list}}
          </ul>
        {{/if}}
      </li>
      {{/inline}}
      {{#* inline "list"}}
        {{#each children}}
          {{> list-item}}
        {{/each}}
        {{/inline}}
```

Main nav:
```html
        <nav>
          <ul>
            {{#each (nestedMenu menu)}}
              {{> list-item}}
            {{/each}}
          </ul>
        </nav>
```

Active menu:
```html
        <nav>
          {{#with (activeMenu menu)}}
            <ul>
              {{#each children}}
                {{> list-item}}
              {{/each}}
            </ul>
          {{/with}}
        </nav>
```

I've also got a breadcrumbs helper planned...

**Comment by turolopezsanabria** [comment]
Thanks a lot @ajbrun 
Unfortunately, I can't make it work :)
I tried many things, but I guess I don't know where exactly to paste the different codes

Can you help me with that as well?
What do I have to do in order to add the JS files to a helpers directory, referenced by the extend configuration option?

Thanks again!
turo

**Comment by ajbrun** [comment]
Hi Turo,

I think this page may help you: https://github.com/kss-node/kss-node/wiki/Extend-template-for-a-custom-block

In your config, there is an extend option - this is the path to your handlebar helper files. The templating system will find any handlebar javascript file in this directory to use in your template. So long as they're there, they should be usable by your handlebars markup in the way that's been shown.

You may find it useful to add a output-object.js file too (I find it helpful for debugging):
`module.exports = (handlebars) => {
    handlebars.registerHelper('outputObject', (object) => {
        return JSON.stringify(object);
    });
};
`

See the handlebars website for more info - it can take a bit of getting use to: http://handlebarsjs.com/

**Comment by turolopezsanabria** [comment]
Great!
It worked perfectly
Thanks a lot

**Comment by ROL4ND909** [comment]
> together with a HandleBars Helper in builder.js
> 
> this.Handlebars.registerHelper('isGrandChild', function(refURI, options) {
>     var fnTrue = options.fn, 
>     fnFalse = options.inverse;
> 
>     return refURI.split('-').length > 2 ? fnTrue(this) : fnFalse(this);
> }); 

How or where did you placed this in the builder.js?

**Comment by LouisClicky** [comment]
Struggling with this too, added the helper correctly and can identify grandchildren just with the base template. However, I cannot display a ul inside of a li item containing the children of that item. 

Tried everything I can find, used #isGrandChildren and then tried each grandChild etc no joy
