### ISSUE TITLE
Nesting issue with Modifiers

### ISSUE THREAD

**Issue by masoomulhaqs** [kss-node/kss-node#415]
# Could anyone please help me fix this.

I want to list all the modifiers in a list but I see that they are generating in a nest. When I comment the `{{{markup}}}` or if change it to `{{markup}}`, I am not seeing that issue.

Below is the required info:

**KSS VERSION:** ` 3.0.0-beta.18`

**HTML CODE:**
``` html
          {{#each modifiers}}
            <div class="kss-modifier__name kss-style">
              {{name}}
            </div>
            <div class="kss-modifier__description kss-style">
              {{{description}}}
            </div>
            <div class="kss-modifier__example clearfix">
              {{{markup}}}
            </div>
          {{/each}}
```

**SCSS CODE:**
``` scss
// Type
//
// Includes classes of various text aligment, colors and sizes.
//
// Markup:
// <div class="{{ modifier_class }}">
//    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
// <div>
//
// .text__right - Align's text to right
// .text__center - Align's text to center
// .text__left - Align's text to left
//
// Weight: 4
//
// Styleguide: Utilities.Type

```

**OUTPUT SCREENSHOT**
![screen shot 2017-06-08 at 9 24 00 pm](https://user-images.githubusercontent.com/9144182/26938216-345f31c4-4c91-11e7-8877-ec9856dcee43.png)

# Could anyone please help me fix this.

**Comment by RobLoach** [comment]
Looks like a missing `</div>` somewhere?

**Comment by masoomulhaqs** [comment]
Yes, I missed `</div>`
