### ISSUE TITLE
Promises not being returned in kss_builder_base

### ISSUE THREAD

**Issue by jmanders85** [kss-node/kss-node#421]
When I run a build with kss@3.0.0-beta.18 in NODE_ENV=development I get warnings in my console about Promises not being returned.  I do not get these errors when NODE_ENV is set to anything else.

`(node:25204) Warning: a promise was created in a handler at /xxx/node_modules/kss/builder/base/kss_builder_base.js:1028:39 but was not returned from it, see http://goo.gl/rRqMUw`

Specifically, I'm using cross-env to set the environment to development and then running my gulp build task.

**Comment by davthu** [comment]
I get the exact same error!

**Comment by joakimbording** [comment]
Same problem here. Need to rely on a fork of esbenjuul's fix to use in production. Please merge!

**Comment by ryuran** [comment]
Fixed by #441 ?

**Comment by RobLoach** [comment]
We could get a release out. Is there anything else we would want to include in it?

**Comment by ssavajols** [comment]
Please, release it ;)

**Comment by ryuran** [comment]
@RobLoach I need my PR #463 in the release if it's possible.

**Comment by ryuran** [comment]
Fixed by #441
