### ISSUE TITLE
Support for white elements

### ISSUE THREAD

**Issue by dahliacreative** [kss-node/kss-node#422]
Hi, I'd like to add a feature request for handling ui components that are white.
Perhaps a comment in the sass to indicate it's a white element, then the build adds a light modifier to the example divs which can have a dark background.

Obviously I could just wrap my markup examples in a div with a dark background, but then it would show up inside my markup sections which is not what I want, as developers could mistake that for real markup.

Or you could have a way of adding additional markup for styling up the examples, but perhaps add a kss-ignore class to them so kss doesn't add those lines to the markup example? That might be more handy as you could use any of your markup used in your site to control the look of your elements, e.g. a ul wrapping and li, but the component is the li on it;s own etc..

Thanks.

**Comment by ryuran** [comment]
You can modify your custom builder to use a custom property as condition to change a classe in your kss demo area.

**Comment by dahliacreative** [comment]
Not sure how to do this, any suggestions on where to start?

**Comment by ryuran** [comment]
# Add a custom property in your json config file.
 
```json
{
  "source": "./css",
  "homepage": "styleguide.md",
  "destination": "./styleguide",
  "builder": "path/to/your/builder",
  "custom": [
    "demoClasses"
  ],
  "css": [
    "../css/styles.css"
  ]
}
```

# Edit you kss template

## If twig (or nunjucks)
`class="kss-modifier__example {{ section.democlasses|default('') }}"` in index.twig of your builder.

https://github.com/kss-node/kss-node/blob/master/builder/twig/index.twig#L178
https://github.com/kss-node/kss-node/blob/master/builder/twig/index.twig#L190

## If handlebars
`class="kss-modifier__example {{ democlasses }}"` in index.hbs of your builder.

https://github.com/kss-node/kss-node/blob/master/builder/handlebars/index.hbs#L181
https://github.com/kss-node/kss-node/blob/master/builder/handlebars/index.hbs#L193

# Edit your styleguide css

Add classe in your styleguide css to have a dark background on `.kss-modifier__example` with your custom class.
```css
.kss-modifier__example.dark {
  background: #000;
}
```

I hope it’s helping @dahliacreative

**Comment by dahliacreative** [comment]
Thanks, that definitely helps! I didn't realise you could add custom properties to your config.

**Comment by dahliacreative** [comment]
Can't seem to get this working, am using KSS with gulp like so:
```
gulp.task('styleguide', () =>
  kss({
    source: paths.src.sass,
    destination: paths.styleguide.root,
    homepage: `../../kss-builder/homepage.md`,
    builder: `${paths.root}/kss-builder`,
    css: `../${dist.root}/stylesheets/application.css`,
    js: `../${dist.root}/javascript/application.js`,
    title: `${paths.name} Styleguide`,
    custom: ['Background']
  })
)
```
I've added it to my comment:
```
// Unclassed Typography
//
// Default typography styles, applied to the body
//
// Markup:
// <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet labore, quo odit debitis natus sit omnis aliquam earum, perspiciatis possimus!</p>
//
// Background: dark
//
// Styleguide Generic.Typography.Unclassed
```
and to my index.hbs:
```
<div class="kss-modifier__wrapper {{ Background }}">
```
but the class isn't getting added, any thoughts?

**Comment by ryuran** [comment]
all variable are in lowercase in template?
Try `<div class="kss-modifier__wrapper {{ background }}">`

**Comment by dahliacreative** [comment]
Thanks that's the one!!
