### ISSUE TITLE
Template comments not included with @import file.scss

### ISSUE THREAD

**Issue by LightBen** [kss-node/kss-node#443]
Hi,

The file used for rendering the whole pattern library is styleguide.scss.

It contains at the beginning imports, like: ```@import "_buttons.scss"```
The import does not contain the comments so KSS doesn't display the elements I wrote in _buttons.scss because the styles don't contain the template comments.
After some research, I saw that it is Sass that keeps multi line comments but removes the single line comments... and knowing that kss works with single line comments for the template, is there a solution here?

PS: I hope I'm not posting this in the wrong GitHub depository, it's my first issue.

Thanks =)

**Comment by LightBen** [comment]
I'm sorry, I just found on CSS Tricks that we can include using KSS comments before the include. I wanted to delete this issue but it looks like it's not possible. If someone wants to take this issue to the next step... 
Hard to find proper documentation though!

**Comment by ryuran** [comment]
You can close this issue.
