### ISSUE TITLE
Path to markup template file

### ISSUE THREAD

**Issue by davthu** [kss-node/kss-node#445]
Is it possible to place the optional markup template (html or hbs) for a given KSS comment in some other location relative to the source file?

**Comment by AndyEPhipps** [comment]
@davthu ... so... is it?

**Comment by jameelmoses** [comment]
@AndyEPhipps yes, the path is relative to the file with the KSS comment

**Comment by davthu** [comment]
@AndyEPhipps  I'm sorry but cant remember anymore. I should have made the comment when it was fresh :-/
