### ISSUE TITLE
raw html output is not tidy

### ISSUE THREAD

**Issue by airtonix** [kss-node/kss-node#448]
Using handlebars and kssnode styleguide dot notated paths as partial names results in example html that is not tidy.

```
Thing

Markup:
<div class="thing {{modifier_class}}">
  <div clas="thing__container">
    {{#if @partial-block}}
      {{> @partial-block}}
    {{else}}
      {{> Styleguide.Box
          modifier_class="styleguide-box--skyblue"
          width="100%"
          height="272px"
        }}
    {{/if}}
  </div>
</div>

Styleguide Core.Components.Thing
```

```
A Complex Thing

Markup:
{{#> Core.Components.Thing modifier_class="thing--has-svg" }}
  <svg something something darkside>
    <use ... >
  </svg>
{{/Core.Components.Thing}}

Styleguide Core.Components.Thing.Complex
```

Results in something roughly like:
```
<div class="thing thing--has-svg">
  <div clas="thing__container">
    <svg something something darkside>
      <use ... >
    </svg>   </div>
</div>
```

when i expected:
```
<div class="thing thing--has-svg">
  <div clas="thing__container">
    <svg something something darkside>
      <use ... >
    </svg>
  </div>
</div>
```

This becomes more of a problem when you're doing something like : 

```
{{> Core.Components.Thing }}
{{> Core.Components.Thing }}
{{> Core.Components.Thing }}
{{> Core.Components.Thing }}
{{> Core.Components.Thing }}
```

I'm aiming for the generated styleguide to be something our backend team and future frontenders can copy paste from, often they are tight with deadlines etc so only change the bare minimum.

Easiest way to solve this is with a html tidy thing? frontend in kss.js or as handlebar helper ? examples?

**Comment by jameelmoses** [comment]
If you're using Gulp, you can add [gulp-prettify](https://github.com/jonschlinkert/gulp-prettify) to the task.

Here's an example:

`gulp.task('twig-compile', () => {

  return gulp.src('src/templates/pages/**/*.twig')
    .pipe(plugins.twig())
    .pipe(plugins.prettify({
      preserve_newlines: true,
      unformatted: ['pre', 'code', 'p']
    }))
    .pipe(gulp.dest('dist'))
  ;
});`

**Comment by airtonix** [comment]
we stopped using gulp for a number of reasons. But I guess I could do this on a post `npm run prod` task.
