### ISSUE TITLE
Replace Sass variables in markup with actual values

### ISSUE THREAD

**Issue by kioueste** [kss-node/kss-node#45]
Hello,

I want to use SASS variables to generate kss doc.

For example, i want implant $base-font-size and $base-line-height

Ii's possible?

**Comment by JohnAlbin** [comment]
The more I think about this feature, the more I realize the problem is trying to get very specific variables out of a CSS preprocessor into the template and displayed in very specific ways in the style guide. I don't think there is a good generic way to do this.
