### ISSUE TITLE
Support for Drupal 8 Attribute methods (e.g. attributes.addClass() )

### ISSUE THREAD

**Issue by Didel** [kss-node/kss-node#458]
This might be related to #288.

I am using kss to generate a style guide which is used in a Drupal theme. Drupal has some specific twig-methods for attributes that allow to add a class to the existing attributes. According to the [Drupal Theming docs](https://www.drupal.org/docs/8/theming-drupal-8/using-attributes-in-templates), using something like `{{ attributes.addClass('my-class') }}` is the preferred way to add/set classes in templates. This is particularly handy when extending other templates (e.g. from the Classy or Stable base-theme).

Currently, this isn't supported by kss, and results in invalid html. For example, when a template is implemented with  `<div{{ attributes.addClass('my-class') }}>...</div>` (which is how Drupal coding-style/standards say you should add classes in your own templates), kss outputs `<divmy-class>...</div>`. 

My current work-around is to include the following in my twig-template:
```twig
{% if not attributes.hasClass('my-class') %}
    {% set attributes = attributes.addClass('my-class') %}
{% endif %}
```

That ensures that kss won't create the messed-up markup mentioned above, but also doesn't add the class properly in kss. That's why I have json-file with content, where I override the complete attributes variable:
```json
{
  "attributes": " class='my-class'"
}
```

This works, but obviously is not the cleanest way to achieve what we want. Implementing this shouldn't be too hard (I guess ? ), and would help a lot in using this for Drupal-themes!

**Comment by RobLoach** [comment]
This is possible: https://github.com/ericmorand/drupal-attribute

**Comment by Kingdutch** [comment]
There's more discussion about this here: #451 

I thought there was a related PR as well but I can't seem to find it.

**Comment by RobLoach** [comment]
Good find! Going to close this one. Let's keep discussions going on over there.
