### ISSUE TITLE
"Error: Cannot find module 'kss/builder' "

### ISSUE THREAD

**Issue by CuriousPhilomath** [kss-node/kss-node#469]
Starting with v 3.0.0-beta.19, getting the error 

`Error: Cannot find module 'kss/builder'`

When attempting to load kss.

It seems to be looking in a different place - or in a different way - as of [this commit](https://github.com/kss-node/kss-node/commit/4c6502f525e9b93d385c6acab91964e83f074c2a)

**Comment by ryuran** [comment]
Sorry @CuriousPhilomath, I think it's my mystake #463.
I don’t know why it's failing.
It’s in should be in this new function https://github.com/kss-node/kss-node/commit/4c6502f525e9b93d385c6acab91964e83f074c2a#diff-acb589513dba3b533821b519a1f4af8aR168

By the way it's working great with an external builder 🙃
