### ISSUE TITLE
Kss installation

### ISSUE THREAD

**Issue by andreyshedko** [kss-node/kss-node#507]
I did installed `kss` as normal npm package into my project via `npm install` from package.json (on Windows 10). But when I'm trying to run command `npm run kss -help` it's not founding `kss`.
How can I fix this?
Node: 8.9.4
npm: 5.6.0

**Comment by RobLoach** [comment]
It should be over at...

```
node_modules/.bin/kss
```

Or similar...

Alternatively, you could add a script for it in package.json...
```
"script": {
  "kss": "kss"
}
```
```
npm run kss
```

**Comment by ryuran** [comment]
`npx kss`
`npx` is natively packed with npm since npm 5.2 and run a node module if found in local `node_modules` or global.

**Comment by DanielRuf** [comment]
I guess we can close this.

My recomnendation is to install it globally.

**Comment by DanielRuf** [comment]
I guess we can close this.

My recommendation is to install it globally.

**Comment by ryuran** [comment]
I agree
