### ISSUE TITLE
Define Custom Property in Builder

### ISSUE THREAD

**Issue by acketon** [kss-node/kss-node#510]
I'm working on creating our own builder based on the base handlebars builder so that we can adjust the index.hbs template. We've created a separate repo for that builder which we are loading as a dependency in our website project.

We also want to add some custom properties which I have working by adding them to the gruntfile in my website project. But since we want to use this kss builder for other unrelated projects I'd like to be able to define the custom properties in the builder so they don't have to be added each time to the kss task in the gruntfile. Is there a way to add a configuration file to the custom builder or some other way to create those custom properties in the builder?

**Comment by ryuran** [comment]
It’s currently possible (not cleanly but possible)
https://github.com/20minutes/colette-kss-builder/blob/master/index.js#L59-L67

**Comment by acketon** [comment]
Thanks, that worked great
