### ISSUE TITLE
@namespace error on Windows 7

### ISSUE THREAD

**Issue by senhduong** [kss-node/kss-node#514]
I get error messages like the following when I try to include a template using a namespace:
TwigException: Unable to find template file C:\xampp\htdocs\apps\theme.test\web\themes\custom\themefolder\C/navigation/navigation.twig

UPDATE: Found the problem. In kss_builder_base_twig.js, at line 76, a namespace is split by a ":" delimiter. For Windows, if the path starts with "C:\" or another drive, then you end up with "namespace:C:\folder\subfolder" which would result in "C" as the path for the namespace.

I encountered this error while using [MediaCurrent's Theme Generator](https://github.com/mediacurrent/theme_generator_8). In one of the gulp tasks, kss namespace is set with __dirname, which is how "C:\" ended up as the path.

**Comment by DanielRuf** [comment]
I'll check that and probably provide a PR.
