### ISSUE TITLE
Deal with context dependent patterns and position fixed

### ISSUE THREAD

**Issue by MoritzGiessmann** [kss-node/kss-node#530]
Hi! 
I was just stumbling upon the fact that if a pattern for example need modifications on the `<body>` element or uses `position: fixed` this code affects the KSS tool itself and not only the patterns, since they get loaded into the same page and context as KSS. 

Example: A header component gets `position: fixed`. Now the element is positioned at the top of the KSS page and not, as expected, inside the example box.

Is there a solution for this I am missing? If this is a usecase maybe putting the patterns in `<iframe>` elements should be considered.

I hope my explanation is clear enough to understand it. I'd be happy to provide you with more information if needed.

Thanks!
Moritz

**Comment by ryuran** [comment]
Hi @MoritzGiessmann.

KSS is designed to document elements and components of a design system. It's currently not adapted to document some page layout.

In your case the header component can be documented, but the position is not relative to the component itself but it's relative to page layout.

In future hope to improve kss to display example in iframe to have a clean css environnent for demos and be able to document `position: fixed`.

**Comment by jameelmoses** [comment]
@MoritzGiessmann A quick option to cover your needs would be to add a class to the body tag of the styleguide and then target it in css and remove the `position: fixed`.

for example:

```
.header {
  position: fixed;

  body.kss-body & {
    position: static;
  }
}
```

**Comment by MoritzGiessmann** [comment]
Thanks for your answers and your ideas!

**Comment by MoritzGiessmann** [comment]
> In future hope to improve kss to display example in iframe to have a clean css environnent for demos and be able to document `position: fixed`.

I'd love to see that! 🙂 

Btw: I love this tool! It's a really awesome and straight forward way to document patterns.
