### ISSUE TITLE
How do I pass an array to a handlebars template?

### ISSUE THREAD

**Issue by wesgro** [kss-node/kss-node#535]
I feel like I'm missing some obvious piece but my Google foo has failed me.

I have a custom Handlebars builder file extending `KssBuilderBaseHandlebars`

What I would like to do is simply pass something like `const myArray = [1,2,3]` to handlebars so from within my handlebars partial file I can go `{{#each myArray}} ...  {{/myArray}}`

I cannot for the life of me find where I am suppose to pass variables to my handlebars templates via the builder file.

**Comment by ryuran** [comment]
I think it's not currently possible without an `option` like `title` in the handlebars base builder.
https://github.com/kss-node/kss-node/blob/master/builder/handlebars/builder.js#L54-L60

https://github.com/kss-node/kss-node/blob/master/builder/handlebars/index.hbs#L5

**Comment by wesgro** [comment]
I think I figured something out but.. I have a feeling this is overly hacky

In my `class KssBuilderHandlebars extends KssBuildBaseHandlebars` I added
```
buildPage(templateName, options, pageReference, sections, context) {
    // Lord forgive me
    sections.forEach(section => {
      const ref = section.toJSON().reference
      if (this.sectionTemplates[ref]) {
        this.sectionTemplates[ref].context = {
          tokens: ['token one', 'token two'],
        }
      }
    })
    return super.buildPage(
      templateName,
      options,
      pageReference,
      sections,
      context
    )
  }
```

This gives me an array called `tokens` in all my partials

**Comment by ryuran** [comment]
It's the way. There is no way les hacky.
The risk is changement of API in futur.
Keep an eye on buildPage function in future release.
I hope to release v3 soin. Beta tag in semver is not comfy.
