### ISSUE TITLE
Markup not displaying

### ISSUE THREAD

**Issue by mituller** [kss-node/kss-node#538]
For some reason, my markup is not displaying. I have the following comments.

```
// Headings
//
// Headings H1-H6
//
// Markup:
//
// <h1 class="text-uppercase">Heading 1</h1>
// <h2 class="text-uppercase">Heading 2</h2>
// <h3 class="text-uppercase">Heading 3</h3>
// <h4 class="text-uppercase">Heading 4</h4>
// <h5 class="text-uppercase">Heading 5</h5>
// <h6 class="text-uppercase">Heading 6</h6>
//
// Style guide: Typography.Headings
```
If I remove the empty comment between Markup: and h1 the markup shows up, but then the styles don't work with the headings. I am using 3.0.3-beta.25 from npm

**Comment by ryuran** [comment]
@mituller
> If I remove the empty comment between Markup: and h1 the markup shows up
Yes, kss-node parser do not accept blank line in markup.

> But then the styles don't work with the headings
This problem seems not related to this kss doc comment.
It could be from your config :
- Are you sure if your css file is set in `css` option ?
- Are you sure if the path is good (no 404 error for your css in debug tools) ?

**Comment by mituller** [comment]
The css location is correct, as all of the styles are displaying as they should. Buttons look correct, etc. I just don't see the markup. I'm including a screenshot of the buttons so you see more that they are set from css.

![image](https://user-images.githubusercontent.com/203721/54446320-a97d7400-4714-11e9-8c89-42ee1f2247ac.png)

**Comment by mituller** [comment]
If I remove the empty line however, I get the markup, but not the styles. 

![image](https://user-images.githubusercontent.com/203721/54446835-e85ff980-4715-11e9-86d1-ce1ee09e0cf8.png)


```
// Buttons
//
// Markup:
//<button type="button" class="btn btn-default">Default</button>
//<button type="button" class="btn btn-primary">Primary</button>
//<button type="button" class="btn btn-danger">Danger</button>
//<button type="button" class="btn btn-warning">Warning</button>
//<button type="button" class="btn btn-info">Info</button>
//<button type="button" class="btn btn-success">Success</button>
//<button type="button" class="btn btn-gray-outline">Gray Outline</button>
//<button type="button" class="btn btn-dark-gray">Dark Gray</button>
//<button type="button" class="btn btn-navy-outline">Navy Outline</button>
//<button type="button" class="btn btn-navy">Navy</button>
//<button type="button" class="btn btn-white-outline">White Outline</button>
//<button type="button" class="btn btn-white">White</button>
//
// Style guide: Buttons.Buttons
```

**Comment by ryuran** [comment]
Ho, it's stange.

Your first case is not correct. Your markup is parsed as "description" and I don't know why "Markup:" is used as markup.

The second case is correct, but I don't know why buttons are not styled. Can you inspect thoses buttons ?
- classes are present ?

What is your builder ?

**Comment by mituller** [comment]
Thank you. That led me to the issue. I have my styles namespaced, so the container needs a style added. I put it in the wrong div, and the buttons just happened to be going to the description instead of where they should. All is good now.

**Comment by ryuran** [comment]
Good to know, so I close this issue
