### ISSUE TITLE
Add additional documentation pages other then Overview

### ISSUE THREAD

**Issue by eddysims** [kss-node/kss-node#539]
More of a question:

Can I have other pages set up other then `overview`? I have kss set up with handlebars builder cloned. 

I would like to add a `guidelines` page that is just a markdown file.

**Comment by ryuran** [comment]
I think it could related to #508

**Comment by nsahlas** [comment]
@eddysims I was looking for the same information and wondered if you found a solution? I would be grateful if you shared anything you found.

**Comment by eddysims** [comment]
@nsahlas no. I ended up just setting up new routes
