### ISSUE TITLE
Ensure HTML tags closed correctly

### ISSUE THREAD

**Issue by sntran** [kss-node/kss-node#544]
Technically, HTML5 allows certain elements without closing tag, such as `<meta>`, `<link>`,  `<img>`. However, in certain environments with strict rules, those elements fails rendering.

Specifically, the `<meta>` and `<link>` generated by `kss-node` do not have closing tags. If you don't mind, I would like to have them closed. I can provide a PR for the default builder.

**Comment by RobLoach** [comment]
Would love to see a Pull Request come up for this! Seems like a great chance to clean up the sources. Thanks.
