### ISSUE TITLE
Source path in generated doc shouldn’t be absolute

### ISSUE THREAD

**Issue by ryuran** [kss-node/kss-node#546]
Since #495 sources path displayed are absolute.

It shouldn't because:

> The generated HTML can be moved to different file system, different server (i.e. Github Pages). We don't want to expose the full file system path of the user generated the HTML. Even so, that Source path is now meaningless when the styleguide is moved.

Thanks @sntran 

https://github.com/kss-node/kss-node/blob/master/lib/traverse.js#L99-L102
should return 
```
{
  base: …,
  path: …,
  contents: …,
}
```
To be used by https://github.com/kss-node/kss-node/blob/master/lib/parse.js#L141

**Comment by DanielRuf** [comment]
Can I provide a PR?

**Comment by ryuran** [comment]
It's fixed by #549
