### ISSUE TITLE
v3.0.1 outputs: "Version 9 of Highlight.js has reached EOL"

### ISSUE THREAD

**Issue by doublethefish** [kss-node/kss-node#582]
Version kss-node v3.0.1 outputs the EOL message for highlight. I notice that this appears to be already fixed on master with an upgrade to HL v10.0.0->10.0.3.

```
Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
```

I assume that the issues discussed in #536 are fixed and the release will fix this issue. Also see #532.

**Comment by muster-mark** [comment]
+1 for making the big scary warning go away every time I `npm install` please.

**Comment by Didel** [comment]
In case it helps, it looks like the same warning is also present when using KSS 3.0.0

**Comment by wholewheattoast** [comment]
Is this ever going to get fixed?  Is anyone actively working on this project any longer?

**Comment by turboteddy** [comment]
@hughsk, @RobLoach, @JohnAlbin and all other [contributors](https://github.com/kss-node/kss-node/graphs/contributors): I (and many others) hope that you'll carry on the great work on [kss-node](https://github.com/kss-node/kss-node)! It's a fantastic piece of work, and a lot of people and organizations have taken it into use ([these](https://github.com/kss-node/kss-node/network/dependents) are only a fraction of them)!

There are clear symptoms of this project no longer being actively maintained (e.g. this [PR](https://github.com/kss-node/kss-node/pull/584) not being merged, [issues piling up](https://github.com/kss-node/kss-node/issues), etc.).

If none of the contributors want / can maintain ownership over kss-node, then please make this explicit and try to find someone who can pick up the baton (e.g. crown one of the [many forks](https://github.com/kss-node/kss-node/network/members) as the official successor. The worst thing that can happen, is not having an official repo that is leading the work on kss-node, thereby getting more and more fragmentation of efforts with half-hearted forks.

I assume that I speak on behalf of many others, and hope that kss-node will live on!!!

**Comment by RobLoach** [comment]
Thanks for the ping. Are you volunteering to help maintain it? 😉... Always open to more collaborators.

**Comment by longnd** [comment]
hi @RobLoach as the PR #584 which fixed this issue has been merged. Would you mind releasing a new version of the package? 🙏

**Comment by RobLoach** [comment]
Release pushed. 3.1.0... There are still some out of date dependencies. Would love some help in updating those!

**Comment by doublethefish** [comment]
Closing as now released.
