### ISSUE TITLE
assets with relative URLs are broken when CSS copied into styleguide

### ISSUE THREAD

**Issue by iancrowther** [kss-node/kss-node#62]
How do i copy over an img dir thats referenced in the css?

**Comment by JohnAlbin** [comment]
> just add <link> tags to the template that includes the CSS without copying it.

Created an issue for that in the 2.x branch: #152

I'm leaving this as an open bug in 1.x.

**Comment by JohnAlbin** [comment]
This is still a bug in 1.x, but since I'm working on 3.x now, I'm going to close this issue. It doesn't appear anyone needs this fixed in 1.x.
