### ISSUE TITLE
Make name of styleguide.md configurable

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#84]
The location of styleguide.md in the middle of my Sass source files has always been a bit odd. It would be nice if the location and name of the file was configurable.

**Comment by JohnAlbin** [comment]
You can specify multiple `--source` directories and kss-node will look in each until it finds a styleguide.md file, so that part of the original issue is fixed.

**Comment by rcaracaus** [comment]
https://github.com/kss-node/kss-node/pull/188

**Comment by JohnAlbin** [comment]
Fixed in 5a812105ab41cc92f61b92053da4e4115c2bfb6c
